export type ChangeType = "added" | "updated" | "improved" | "fixed";

export interface ChangelogItem {
  id: string;
  date: string; // YYYY-MM-DD
  title: string;
  type: ChangeType;
  toolHref?: string;
  toolName?: string;
  description: string;
  highlights?: string[];
}

export const CHANGELOG_ITEMS: ChangelogItem[] = [
  {
    id: "2026-09-28-seven-tools-critical-fixes",
    date: "2026-09-28",
    title: "Seven New Tools Critical Fixes",
    type: "fixed",
    toolHref: "/openapi-to-ts",
    toolName: "New Developer Tools",
    description: "Fixed critical schema, serializer, color parsing, and rotated crop correctness issues found during acceptance review.",
    highlights: ["Sanitized generated OpenAPI identifiers and preserved nullable and enum semantics", "Improved Python request serialization and form handling", "Corrected rotated image crop export coordinates", "Added RGB(A) and HSL(A) color input parsing"],
  },
  {
    id: "2026-09-28-gitignore-generator-criteria-hardening",
    date: "2026-09-28",
    title: "Gitignore Generator Improvements",
    type: "improved",
    toolHref: "/gitignore-generator",
    toolName: "Gitignore Generator",
    description: "Expanded gitignore generation with categorized presets, readable sections, deterministic composition, and file download.",
    highlights: ["Added framework, runtime, OS, editor, and container preset groups", "Preserves negation order while deduplicating patterns", "Added reset, copy, and .gitignore download actions"],
  },
  {
    id: "2026-09-28-image-cropper-criteria-hardening",
    date: "2026-09-28",
    title: "Image Cropper Interaction Improvements",
    type: "improved",
    toolHref: "/image-cropper",
    toolName: "Image Cropper & Resizer",
    description: "Added crop ratio presets and synchronized rotation preview while preserving mouse and touch controls.",
    highlights: ["Added Free, 1:1, 4:3, and 16:9 crop presets", "Corner-only resize behavior is explicitly documented", "Rotation preview now matches exported output"],
  },
  {
    id: "2026-09-28-color-converter-criteria-hardening",
    date: "2026-09-28",
    title: "Color Converter Accessibility and Format Expansion",
    type: "improved",
    toolHref: "/color-converter-pro",
    toolName: "Color Converter Pro",
    description: "Expanded color conversion with alpha formats, LAB, OKLCH, generated palettes, and WCAG contrast checks.",
    highlights: ["Supports 3, 4, 6, and 8 digit HEX values", "Added LAB and OKLCH output", "Added generated tint/shade palette and accessible foreground guidance"],
  },
  {
    id: "2026-09-28-env-editor-criteria-hardening",
    date: "2026-09-28",
    title: "Environment File Parsing Improvements",
    type: "fixed",
    toolHref: "/env-file-editor",
    toolName: "ENV File Editor",
    description: "Improved .env parsing, duplicate diagnostics, secret masking, example generation, and deterministic JSON export.",
    highlights: ["Handles export prefixes, quoted values, comments, and quoted hash characters", "Reports duplicate keys with line numbers", "Preserves source lines and warns about duplicate JSON keys"],
  },
  {
    id: "2026-09-28-http-builder-criteria-hardening",
    date: "2026-09-28",
    title: "HTTP Request Builder Improvements",
    type: "fixed",
    toolHref: "/http-request-builder",
    toolName: "HTTP Request Builder",
    description: "Expanded request snippet generation with query parameters, authentication, body modes, validation, and safer serializers.",
    highlights: ["Added Bearer, Basic, and API key authentication modes", "Added query parameter and JSON, form, and raw body controls", "Improved cURL, fetch, Axios, and Python output safety"],
  },
  {
    id: "2026-09-28-jsonl-analyzer-criteria-hardening",
    date: "2026-09-28",
    title: "JSONL Analyzer Acceptance Hardening",
    type: "fixed",
    toolHref: "/jsonl-analyzer",
    toolName: "JSONL Analyzer",
    description: "Expanded JSONL analysis with physical line accounting, parse diagnostics, schema drift, and exportable reports.",
    highlights: [
      "Preserves blank lines and reports total, valid, invalid, and blank counts",
      "Shows invalid line numbers with parser errors and copyable report",
      "Profiles object fields, observed types, and missing or extra schema fields",
      "Safely counts primitive and array records while keeping processing client-side",
    ],
  },
  {
    id: "2026-09-28-openapi-criteria-hardening",
    date: "2026-09-28",
    title: "OpenAPI Schema Conversion Hardening",
    type: "fixed",
    toolHref: "/openapi-to-ts",
    toolName: "OpenAPI to TypeScript",
    description: "Hardened OpenAPI 3 schema conversion with validation, safe property names, nested types, and actionable parse errors.",
    highlights: [
      "Validates OpenAPI 3.x documents and clearly rejects unsupported Swagger 2.x input",
      "Supports nested objects, arrays, enums, composition, nullable primitives, and additional properties",
      "Produces safer TypeScript and Zod output for unusual property names",
      "Preserves input on parse errors and reports actionable feedback",
    ],
  },
  {
    id: "2026-09-25-image-crop-mouse-resize",
    date: "2026-09-25",
    title: "Mouse-Resizable Crop Rectangle",
    type: "improved",
    toolHref: "/image-cropper",
    toolName: "Image Cropper & Resizer",
    description: "Added interactive corner handles so the crop rectangle can be resized directly with the mouse or touch pointer.",
    highlights: [
      "Drag any of the four green corner handles to resize the crop rectangle",
      "Drag inside the rectangle to reposition it",
      "Aspect-ratio lock is respected during handle resizing",
      "Crop dimensions remain bounded by the source image",
    ],
  },
  {
    id: "2026-09-25-image-cropper-workflow-improved",
    date: "2026-09-25",
    title: "Image Cropper Workflow Improvements",
    type: "improved",
    toolHref: "/image-cropper",
    toolName: "Image Cropper & Resizer",
    description: "Reworked the image cropper into an interactive crop-and-resize workflow with clear photo replacement controls.",
    highlights: [
      "Choose Photo and Replace Photo actions make changing the source image explicit",
      "Drag the crop rectangle preview to reposition the crop area",
      "Separate Crop Rectangle and Output Resize controls with optional aspect-ratio locking",
      "Reset crop, rotate, choose PNG/JPEG/WebP, and download the processed result",
    ],
  },
  {
    id: "2026-09-25-openapi-image-cropper-fixes",
    date: "2026-09-25",
    title: "OpenAPI Parser & Image Cropper Functionality Fixes",
    type: "fixed",
    toolHref: "/openapi-to-ts",
    toolName: "OpenAPI to TypeScript & Zod",
    description: "Corrected OpenAPI document parsing and upgraded Image Cropper from basic resizing to a real crop-and-export workflow.",
    highlights: [
      "OpenAPI converter now accepts JSON and YAML input through the existing js-yaml dependency",
      "Added TypeScript interface/type and Zod generation for refs, arrays, enums, unions, and formats",
      "Image Cropper now uses an actual x/y/width/height crop rectangle with live Canvas preview",
      "Added 90-degree rotation and PNG, JPEG, and WebP crop downloads",
    ],
  },
  {
    id: "2026-09-25-seven-new-developer-tools",
    date: "2026-09-25",
    title: "Seven New Local-First Developer Tools",
    type: "added",
    toolHref: "/openapi-to-ts",
    toolName: "OpenAPI to TypeScript & Zod",
    description: "Added seven browser-only tools for API schemas, environment files, project setup, JSONL data, HTTP requests, colors, and images.",
    highlights: [
      "OpenAPI to TypeScript & Zod schema generator",
      "Environment file editor with .env.example sanitization and JSON export",
      "Gitignore generator with framework, language, OS, and editor presets",
      "JSONL analyzer, HTTP Request Builder, Color Studio, and Image Cropper",
    ],
  },
  {
    id: "2026-09-24-json-repair-and-layout-fixes",
    date: "2026-09-24",
    title: "LLM JSON Trailing Prose & SQL Tool Header Fixes",
    type: "fixed",
    toolHref: "/json-repair",
    toolName: "JSON Repair & SQL to TS",
    description: "Fixed trailing conversational prose stripping in LLM JSON Repair and eliminated header button collisions in SQL to TypeScript converter.",
    highlights: [
      "Fixed LLM JSON Repair parser: automatically strips trailing prose/commentary after root JSON closing bracket",
      "Resolved CSS flex header collision in SQL to TS by moving configuration toggles to a dedicated responsive settings panel",
      "Improved EVM Calldata Decoder with canonical ABI selector matching and fixed BigInt text-wrapping in word inspector",
      "Enhanced PDF Metadata Editor with 1-click sample document loader and per-field population status indicators",
    ],
  },
  {
    id: "2026-09-24-sql-to-ts",
    date: "2026-09-24",
    title: "SQL DDL to TypeScript & Zod Schema",
    type: "added",
    toolHref: "/sql-to-ts",
    toolName: "SQL to TypeScript & Zod",
    description: "Convert SQL CREATE TABLE statements into strongly-typed TypeScript interfaces, type aliases, and Zod schemas with customizable casing and nullability.",
    highlights: [
      "Parses multi-table CREATE TABLE DDL from PostgreSQL, MySQL, and SQLite dialects",
      "Maps SQL data types (serial, uuid, jsonb, timestamp, arrays) to standard TypeScript & Zod equivalents",
      "Configurable snake_case vs camelCase naming and union (| null) vs optional (?) nullable styles",
      "100% private in-browser regex AST tokenizer with zero database connection required",
    ],
  },
  {
    id: "2026-09-24-evm-calldata-decoder",
    date: "2026-09-24",
    title: "EVM Calldata Decoder & ABI Inspector",
    type: "added",
    toolHref: "/evm-calldata-decoder",
    toolName: "EVM Calldata Decoder",
    description: "Milestone 100th Tool! Decode raw Ethereum and EVM transaction calldata hex into formatted parameters and 32-byte memory word slices.",
    highlights: [
      "Auto-detects 4-byte selectors for common ERC-20, ERC-721, and DEX functions",
      "Decodes method parameters into EIP-55 checksummed addresses, BigInts, and Ether equivalents",
      "Slices raw memory into 32-byte chunks with hex, uint, address, and ASCII representations",
      "100% client-side Web Crypto and BigInt engine with zero RPC leak risk",
    ],
  },
  {
    id: "2026-09-24-semver-calculator",
    date: "2026-09-24",
    title: "Semantic Versioning Calculator & Range Tester",
    type: "added",
    toolHref: "/semver-calculator",
    toolName: "SemVer Calculator & Range Tester",
    description: "Launched an interactive SemVer 2.0 calculator with range expression evaluator, 1-click version bumping, and multi-version precedence sorting.",
    highlights: [
      "Decomposes semantic version into Major, Minor, Patch, Pre-release, and Build metadata",
      "Evaluates complex dependency ranges including ^, ~, >=, <=, and logical || sets",
      "Simulates 1-click version bumps for major, minor, patch, alpha, beta, and rc tags",
      "Features multi-version list sorter following official SemVer 2.0 precedence rules",
    ],
  },
  {
    id: "2026-09-24-pdf-metadata-editor",
    date: "2026-09-24",
    title: "PDF Metadata Editor & Sanitizer",
    type: "added",
    toolHref: "/pdf-metadata-editor",
    toolName: "PDF Metadata Editor & Sanitizer",
    description: "Inspect, update, or 1-click purge confidential document metadata properties from PDF files with zero server exposure.",
    highlights: [
      "View and edit Title, Author, Subject, Keywords, Creator, and Producer properties",
      "1-Click 'Strip All Metadata' button to instantly sanitize documents for private sharing",
      "Full local browser execution powered by pdf-lib with zero data upload",
    ],
  },
  {
    id: "2026-09-24-json-repair",
    date: "2026-09-24",
    title: "LLM JSON Repair & Auto-Fixer",
    type: "added",
    toolHref: "/json-repair",
    toolName: "LLM JSON Repair & Auto-Fixer",
    description: "Launched in-browser JSON repair tool specifically designed to fix malformed, truncated, and poorly formatted LLM outputs.",
    highlights: [
      "Automatically strips markdown code fence wrappers and surrounding conversational prose",
      "Converts single quotes, fixes unquoted object keys, and strips trailing commas",
      "Auto-closes unterminated brackets and braces from truncated LLM streaming responses",
      "100% private in-browser AST & token repair with zero data transmission",
    ],
  },
  {
    id: "2026-09-17-search-and-pdf-fixes",
    date: "2026-09-17",
    title: "Command Palette Search & PDF Organizer UX Improvements",
    type: "improved",
    toolHref: "/pdf-organizer",
    toolName: "Search & PDF Organizer",
    description: "Enhanced global search palette with capture-phase Escape key dismissal and added Clear/Change PDF controls to PDF Organizer.",
    highlights: [
      "Capture-phase Escape key and backdrop dismissal on Command Palette search",
      "Added [Clear / Change PDF] action button to PDF Page Rotator & Reorder Grid",
      "Instant state and memory buffer cleanup on document reset",
    ],
  },
  {
    id: "2026-09-17-graphql-formatter",
    date: "2026-09-17",
    title: "GraphQL Query Beautifier & AST Inspector",
    type: "added",
    toolHref: "/graphql-formatter",
    toolName: "GraphQL Query Beautifier",
    description: "Format, prettify, minify, and extract variables or operation AST metrics from GraphQL queries and mutations.",
    highlights: [
      "Prettify and minify GraphQL queries, mutations, and subscriptions",
      "Automatic AST extraction for operation name, root fields, and query variables",
      "Query Payload Bundler generating HTTP POST payloads for fetch() and cURL",
      "100% client-side execution with zero data leakage"
    ],
  },
  {
    id: "2026-09-17-cron-simulator",
    date: "2026-09-17",
    title: "Crontab Schedule Visualizer & Next 20 Executions Calendar",
    type: "added",
    toolHref: "/cron-simulator",
    toolName: "Crontab Visualizer",
    description: "Simulate cron schedules, calculate next 20 upcoming execution timestamps in local/UTC time, and visualize active hours heatmap.",
    highlights: [
      "Real-time plain English schedule explanation from 5-field cron syntax",
      "Live countdown timer to next trigger event",
      "Precise calculation of next 20 upcoming execution timestamps in local and UTC",
      "Built-in presets for common server automation schedules"
    ],
  },
  {
    id: "2026-09-17-regex-explainer",
    date: "2026-09-17",
    title: "Regex Visual Explainer & AST Token Breakdown",
    type: "added",
    toolHref: "/regex-explainer",
    toolName: "Regex Visual Explainer",
    description: "Deconstruct regular expressions into clear plain-English token explanations, lookarounds, capture groups, and quantifier breakdowns.",
    highlights: [
      "Interactive color-coded token stream chips (Anchors, Sets, Quantifiers, Groups)",
      "Step-by-step plain English explanations for every regular expression token",
      "Support for lookaheads, lookbehinds, non-capturing groups, and greedy/lazy modifiers",
      "One-click copy of full regex documentation report"
    ],
  },
  {
    id: "2026-09-17-json-to-csv",
    date: "2026-09-17",
    title: "JSON to CSV / TSV Converter & Table Exporter",
    type: "added",
    toolHref: "/json-to-csv",
    toolName: "JSON to CSV Exporter",
    description: "Convert JSON arrays and nested structures into clean CSV, TSV, or interactive data grids with automatic key flattening.",
    highlights: [
      "Automatic recursive key flattening for deep nested JSON objects (e.g. user.address.city)",
      "Multi-delimiter support (CSV, TSV, Semicolon, Pipe)",
      "Interactive data grid table preview with live row/column counters",
      "Direct .csv / .tsv file download with UTF-8 support"
    ],
  },
  {
    id: "2026-09-15-robots-generator",
    date: "2026-09-15",
    title: "Robots.txt Generator & Live Path Match Tester",
    type: "added",
    toolHref: "/robots-generator",
    toolName: "Robots.txt Generator",
    description: "Construct standard robots.txt files with AI bot blocking (GPTBot, ClaudeBot), crawl delays, and live URL matching simulation.",
    highlights: [
      "Real-time URL match tester simulating crawler decisions (Allowed vs Blocked)",
      "Built-in presets to block aggressive AI training scrapers (GPTBot, ClaudeBot, CCBot, ByteSpider)",
      "Standard RFC 9309 compliant rule ordering and canonical sitemap declaration",
      "One-click direct .txt download with zero server leakage"
    ],
  },
  {
    id: "2026-09-15-user-agent-parser",
    date: "2026-09-15",
    title: "User-Agent String Parser & Client Hints Inspector",
    type: "added",
    toolHref: "/user-agent-parser",
    toolName: "User-Agent String Parser",
    description: "Parse User-Agent strings to detect browser versions, OS architecture, device models, and AI search crawler bots.",
    highlights: [
      "Accurate detection of browser engine, major release, OS build, and CPU architecture",
      "Integrated Bot & Crawler identifier for search engines and LLM crawlers",
      "One-click [My Browser UA] client detection and Client Hints inspection",
      "Clean JSON device profile export"
    ],
  },
  {
    id: "2026-09-15-har-viewer",
    date: "2026-09-15",
    title: "HAR File Viewer & Network Waterfall Analyzer",
    type: "added",
    toolHref: "/har-viewer",
    toolName: "HAR File Viewer",
    description: "Inspect HTTP Archive (.har) logs with visual waterfall timelines, TTFB metrics, SSL/DNS timings, and request headers.",
    highlights: [
      "Interactive visual waterfall timeline with millisecond timing breakdowns (DNS, Connect, SSL, TTFB, Download)",
      "Filter requests by HTTP status (2xx, 3xx, 4xx, 5xx) and content types (XHR, JS, CSS, Img)",
      "Deep inspector for request/response headers, query params, and JSON response bodies",
      "100% private in-browser memory analysis without uploading sensitive HAR logs"
    ],
  },
  {
    id: "2026-09-15-csp-builder",
    date: "2026-09-15",
    title: "Content Security Policy (CSP) Builder & Security Auditor",
    type: "added",
    toolHref: "/csp-builder",
    toolName: "Content Security Policy Builder",
    description: "Construct, analyze, and test hardened Content Security Policy (CSP) headers with cryptographic nonces and security audit.",
    highlights: [
      "Visual directive builder for script-src, style-src, img-src, connect-src, and frame-ancestors",
      "Real-time security audit identifying unsafe-inline, unsafe-eval, and missing object-src directives",
      "Integrated 128-bit cryptographic nonce generator",
      "Multi-target output for HTTP Header, HTML Meta, Nginx, Apache, Vercel, and Next.js"
    ],
  },
  {
    id: "2026-09-15-llm-diff-comparator",
    date: "2026-09-15",
    title: "LLM Output Diff & Hallucination Spotter: Side-by-Side Comparator",
    type: "added",
    toolHref: "/llm-diff-comparator",
    toolName: "LLM Output Diff & Hallucination Spotter",
    description: "Compare AI model outputs side-by-side with word-level diff, numerical discrepancy analysis, and hallucination detection.",
    highlights: [
      "Word-level and line-level diff highlighting with Jaccard semantic similarity metric",
      "Automatic quantitative and percentage discrepancy extraction to spot hallucinations",
      "Multi-mode view: Side-by-side editor, Unified line diff, and Discrepancy inspector",
      "100% client-side computation with zero external API dependencies"
    ],
  },
  {
    id: "2026-09-15-few-shot-formatter",
    date: "2026-09-15",
    title: "Few-Shot Prompt & Fine-Tuning Dataset Formatter: OpenAI JSONL & ChatML",
    type: "added",
    toolHref: "/few-shot-formatter",
    toolName: "Few-Shot Prompt & Fine-Tuning Formatter",
    description: "Construct, validate, and convert few-shot prompt examples into OpenAI JSONL, Anthropic XML, ChatML, and Llama 3 templates.",
    highlights: [
      "Interactive few-shot pair builder with system persona and ground-truth responses",
      "Export to OpenAI JSONL, Anthropic XML tags, ChatML, Llama 3 header syntax, TS Array, and CSV",
      "Built-in presets for classification, SQL generation, and named entity extraction",
      "Zero server leakage with direct in-browser dataset file download"
    ],
  },
  {
    id: "2026-09-15-token-counter",
    date: "2026-09-15",
    title: "LLM Token Counter & API Cost Estimator: Real-Time Pricing Matrix",
    type: "added",
    toolHref: "/token-counter",
    toolName: "LLM Token Counter & API Cost Estimator",
    description: "Count BPE tokens, preview subword segments, and calculate real-time API inference costs across OpenAI, Claude, Gemini, and DeepSeek.",
    highlights: [
      "Instant token, character, word count, and reading duration calculations",
      "Real-time cost matrix covering 9 flagship & budget models (GPT-4o, Claude 3.5 Sonnet, Gemini 1.5, DeepSeek V3/R1)",
      "Visual Tokenizer rendering color-coded BPE subword segments",
      "Projected generation output sliders and batch request multiplier"
    ],
  },
  {
    id: "2026-09-04-pdf-watermark",
    date: "2026-09-04",
    title: "PDF Watermark & Stamp Studio: Vector Overlay Engine",
    type: "added",
    toolHref: "/pdf-watermark",
    toolName: "PDF Watermark & Stamp Studio",
    description: "Added a client-side vector watermark stamping tool to overlay customizable text (CONFIDENTIAL, DRAFT), rotation angles, and opacity across all pages of a PDF.",
    highlights: [
      "100% private in-browser vector text stamping with pdf-lib and Helvetica font embedding",
      "Interactive A4 page simulator rendering live rotation and opacity adjustments",
      "Customizable angle (-90° to 90°), font size, opacity (5% - 100%), and color palette",
      "One-click multi-page batch stamping and instant clean PDF compilation",
    ],
  },
  {
    id: "2026-09-04-tone-generator",
    date: "2026-09-04",
    title: "Web Audio Tone & Frequency Synthesizer: Real-Time Oscilloscope",
    type: "added",
    toolHref: "/tone-generator",
    toolName: "Web Audio Tone & Frequency Synthesizer",
    description: "Added a Web Audio synthesizer generating pure tones (20Hz - 20kHz), stereo binaural beats, and colored noise (white, pink, brown) with an interactive canvas oscilloscope.",
    highlights: [
      "Pure sinusoidal, square, sawtooth, and triangle wave generation with pitch presets",
      "Stereo binaural beats with carrier and target brainwave frequency differential (Delta to Beta)",
      "White, pink, and brown colored noise generators with octave attenuation filters",
      "Live HTML5 Canvas oscilloscope displaying real-time FFT time-domain waveform oscillations",
    ],
  },
  {
    id: "2026-09-04-rdap-lookup",
    date: "2026-09-04",
    title: "RDAP Domain & Registration Inspector: Modern WHOIS Protocol",
    type: "added",
    toolHref: "/rdap-lookup",
    toolName: "RDAP Domain & IP Registration Inspector",
    description: "Launched an authoritative domain and IP registration lookup utility querying official ICANN RESTful RDAP registries with status lock flags, expiration dates, and nameservers.",
    highlights: [
      "Modern HTTP REST replacement for legacy port-43 WHOIS queries",
      "Direct authoritative lookup via Verisign, Public Interest Registry, and ARIN",
      "Inspects domain status flags, creation dates, expiration countdown, and registrar details",
      "IPv4/IPv6 network block and CIDR allocation inspection",
    ],
  },
  {
    id: "2026-09-04-data-url",
    date: "2026-09-04",
    title: "Base64 Data URL & Asset Embedder: Instant Inlining Studio",
    type: "added",
    toolHref: "/data-url",
    toolName: "Base64 Data URL & Asset Embedder",
    description: "Added a client-side Data URI conversion utility to inline images, fonts, and SVGs into ready-to-use CSS rules, HTML tags, and JavaScript imports with transmission overhead metrics.",
    highlights: [
      "Instant drag-and-drop conversion for PNG, JPG, WebP, SVG, WOFF2, and JSON files",
      "One-click code snippets: RFC 2397 Data URI, CSS background-image, and HTML <img> element",
      "Real-time Base64 size inflation tracker comparing raw bytes against encoded payload (+33%)",
      "Live visual preview for raster images and vector SVG markup",
    ],
  },
  {
    id: "2026-09-04-bip39-generator",
    date: "2026-09-04",
    title: "BIP-39 Mnemonic Seed Studio: Airgapped Key Generation",
    type: "added",
    toolHref: "/bip39-generator",
    toolName: "BIP-39 Mnemonic Seed Phrase Studio",
    description: "Added a 100% offline BIP-39 recovery phrase generator with CSPRNG entropy sampling, official 2048-word dictionary verification, and PBKDF2 512-bit master seed derivation.",
    highlights: [
      "12-word (128-bit) and 24-word (256-bit) CSPRNG entropy generation via Web Crypto",
      "Full SHA-256 checksum calculation with raw entropy hex breakdown",
      "PBKDF2-HMAC-SHA512 2,048-iteration seed derivation with optional salt passphrase",
      "Offline Mnemonic Validator to test recovery phrases against the official BIP-39 standard",
    ],
  },
  {
    id: "2026-09-04-pdf-organizer",
    date: "2026-09-04",
    title: "PDF Page Rotator & Reorder Grid: Visual Client-Side Assembly",
    type: "added",
    toolHref: "/pdf-organizer",
    toolName: "PDF Page Rotator & Reorder Grid",
    description: "Launched an airgapped visual PDF organizer to reorder page sequences, rotate individual or all pages, and remove unwanted pages with in-browser compilation.",
    highlights: [
      "Interactive visual card grid displaying page dimensions, order, and rotation status",
      "Per-page and global 90°/180°/270° orientation rotation controls",
      "One-click directional reordering, reverse ordering, and page removal",
      "100% private in-memory compilation with pdf-lib — zero server uploads",
    ],
  },
  {
    id: "2026-09-04-prompt-architect",
    date: "2026-09-04",
    title: "Structured System Prompt Architect: Anti-Hallucination XML Engine",
    type: "added",
    toolHref: "/prompt-architect",
    toolName: "Structured System Prompt Architect",
    description: "Added an advanced prompt engineering studio to construct hardened system prompts with explicit persona roles, negative constraints, output formats, and few-shot examples.",
    highlights: [
      "Industry-standard Anthropic XML and OpenAI Markdown synthesis",
      "Interactive guardrail builder with dynamic constraint management",
      "Pre-configured battle-tested archetypes: Code Reviewer, Strict RAG Agent, JSON Extractor",
      "One-click export directly formatted for official LLM API JSON payloads",
    ],
  },
  {
    id: "2026-09-04-rag-chunker",
    date: "2026-09-04",
    title: "RAG Document Chunker: Recursive Splitting & Overlap Engine",
    type: "added",
    toolHref: "/rag-chunker",
    toolName: "RAG Document Chunker",
    description: "Launched an interactive text chunking studio for RAG and Vector DB preparation with recursive splitting, boundary overlap visualizer, and Pinecone/Qdrant JSON export.",
    highlights: [
      "Recursive character splitting prioritizing natural paragraph (\n\n) and sentence boundaries",
      "Dynamic chunk size (100 - 2,000 chars) and contextual overlap window configuration",
      "Visual card breakdown with overlap prefix highlights and token estimates",
      "One-click Vector DB ingestion export (JSON and JSONL schema with metadata)",
    ],
  },
  {
    id: "2026-09-04-dns-lookup",
    date: "2026-09-04",
    title: "DNS over HTTPS (DoH) Lookup & Records Inspector",
    type: "added",
    toolHref: "/dns-lookup",
    toolName: "DNS over HTTPS Lookup",
    description: "Added an encrypted browser-based DNS lookup tool powered by Cloudflare (1.1.1.1) and Google (8.8.8.8) DoH JSON resolvers with DNSSEC verification.",
    highlights: [
      "Query A, AAAA, MX, TXT, CNAME, NS, SOA, CAA, and PTR records directly from the browser",
      "Switch seamlessly between Cloudflare and Google DoH endpoints",
      "DNSSEC Authenticated Data (AD) flag inspection and TTL countdown metrics",
      "All-in-one 'ALL' mode to aggregate host IP, mail servers, and text verification records simultaneously",
    ],
  },
  {
    id: "2026-09-04-webrtc-leak",
    date: "2026-09-04",
    title: "WebRTC IP Leak & VPN Shield Tester: In-Browser STUN Probe",
    type: "added",
    toolHref: "/webrtc-leak",
    toolName: "WebRTC IP Leak & VPN Shield Tester",
    description: "Added an automated WebRTC diagnostic tool to verify if your real WAN or LAN IP leaks past VPN or proxy tunnels through STUN ICE candidate requests.",
    highlights: [
      "Probes public Google STUN servers to detect server-reflexive (srflx) and host candidates",
      "Automatic side-by-side comparison between WebRTC candidates and HTTP egress IP",
      "Detects mDNS anonymization vs actual multi-homed IP exposure",
      "Actionable remediation guides for hardening Firefox, Brave, Chrome, and Edge",
    ],
  },
  {
    id: "2026-09-04-pwned-checker",
    date: "2026-09-04",
    title: "Pwned Password Checker: HaveIBeenPwned k-Anonymity Engine",
    type: "added",
    toolHref: "/pwned-checker",
    toolName: "Pwned Password & Data Breach Checker",
    description: "Launched an airgapped data breach password scanner using mathematical k-Anonymity — verify password exposures in 800M+ leaked records with zero plaintext leakage.",
    highlights: [
      "Mathematical k-Anonymity guarantee — only 5-hex SHA-1 prefix is ever queried against HIBP",
      "Exact breach exposure count and threat severity classification (Extreme, High, Compromised)",
      "Real-time prefix/suffix cryptographic pipeline visualization",
      "Immediate security recommendations and 100% in-browser hash computation",
    ],
  },
  {
    id: "2026-09-04-secret-scanner",
    date: "2026-09-04",
    title: "Secret & API Key Leak Scanner: Client-Side Credential Defense",
    type: "added",
    toolHref: "/secret-scanner",
    toolName: "Secret & API Key Leak Scanner",
    description: "Launched an airgapped credential leak scanner with regex heuristics and Shannon entropy analysis to detect leaked tokens and auto-sanitize source code.",
    highlights: [
      "100% client-side inspection — zero code or secrets ever leave your browser",
      "Detects 14+ credential signatures including AWS, GitHub, OpenAI, Anthropic, Google, Stripe, Slack, and database URIs",
      "Shannon entropy calculation to surface high-entropy pseudo-random secrets lacking standard prefixes",
      "1-Click Auto-Masking to sanitize sensitive files before committing to Git or sharing publicly",
    ],
  },
  {
    id: "2026-09-03-binary-converter-omnidirectional",
    date: "2026-09-03",
    title: "Binary & Base Converter: Omnidirectional Multi-Input",
    type: "improved",
    toolHref: "/binary-converter",
    toolName: "Binary & Base Converter",
    description: "Upgraded the converter to support full omnidirectional input. Edit any of the 6 data representations in real time to synchronize all other formats automatically.",
    highlights: [
      "All 6 representations (Text UTF-8, Binary 8-bit, Hexadecimal, Base58, Base32, Decimal) are now editable inputs",
      "Editing any field automatically decodes and updates all other fields instantaneously",
      "Inline error validation per field (e.g. invalid base58 characters or odd-length hex) without overwriting valid data",
      "Quick action Reset Sample and Clear All buttons with per-field copy buttons",
    ],
  },
  {
    id: "2026-08-31-ai-model-comparator-overhaul",
    date: "2026-08-31",
    title: "AI Model Comparator: Native models.dev Dataset & Advanced Sorting",
    type: "improved",
    toolHref: "/ai-model-comparator",
    toolName: "AI Model Comparator",
    description: "Overhauled the AI Model Comparator to ingest the native models.dev schema verbatim, adding frontier model metrics, context window filters, and smart release sorting.",
    highlights: [
      "Direct models.dev open dataset integration powering real-time frontier LLM comparisons",
      "Default sorting by newest release date with toggleable price, context length, and modality sorting",
      "Comprehensive token pricing breakdown per 1M tokens (input, output, cached, reasoning)",
      "Context window and parameter size filters covering major labs (OpenAI, Anthropic, Google, Meta, DeepSeek)",
    ],
  },
  {
    id: "2025-05-16-batch-6-blockchain-ai",
    date: "2025-05-16",
    title: "8 New Blockchain & AI Engineering Utilities (73 Total)",
    type: "added",
    description: "Expanded the tool catalog with 5 in-browser cryptographic Web3 tools and 3 AI/LLM engineering utilities with models.dev sync support.",
    highlights: [
      "Blockchain: Ethereum Unit & Gas Fee Calculator (Wei/Gwei/ETH), EIP-55 Address Checksum & Validator",
      "Blockchain: Solana SOL/Lamports & Ed25519 Inspector, Keccak-256 Hasher & 4-Byte Selector, Merkle Tree & Airdrop Proof Builder",
      "AI & LLM: AI Model Pricing & Context Matrix (models.dev live sync), Universal Multi-Provider Payload Exporter, Vector Cosine Similarity Calculator",
    ],
  },
  {
    id: "2025-05-15-cyber-terminal-boot",
    date: "2025-05-15",
    title: "Cyber Terminal UI, Boot Sequence & Tmux Telemetry",
    type: "added",
    description: "Enhanced the interface with an authentic terminal experience including Linux kernel boot animation, live telemetry status bar, and CRT scanlines.",
    highlights: [
      "Cyber kernel boot sequence splash screen with quick skip and replay",
      "Realtime Tmux telemetry status bar with UTC clock, memory heap, and 0ms latency",
      "Retro CRT scanline mode with persistent header toggle",
      "ASCII Art glowing hero banner with interactive grep search",
      "Standardized 2-column input/output alignment across converter tools",
    ],
  },
  {
    id: "2025-05-15-notifications-changelog",
    date: "2025-05-15",
    title: "Changelog & Live Notification System",
    type: "added",
    toolHref: "/changelog",
    toolName: "Changelog",
    description: "Added in-app notification bell and dedicated changelog page to keep track of new tools, major updates, and bug fixes.",
    highlights: [
      "Real-time unread badge indicator with local storage sync",
      "Quick notification popover in header",
      "Dedicated /changelog timeline page with type filtering",
    ],
  },
  {
    id: "2025-05-10-batch-5-tools",
    date: "2025-05-10",
    title: "12 New Developer, Media, & Security Utilities",
    type: "added",
    description: "Expanded the tool catalog to 65 total tools with new utilities for developers, audio/video editing, and cybersecurity.",
    highlights: [
      "Network Tools: DNS Lookup, Subnet Calculator, Port Scanner Simulator",
      "Security: CSR Generator, SSL Certificate Decoder, Hash Cracker Simulator",
      "Media: Audio Pitch/Speed Shifter, Video Frame Extractor",
      "Developer: Crontab Guru, JSON to Typescript, SQL to Prisma",
    ],
  },
  {
    id: "2025-05-02-seo-indexnow",
    date: "2025-05-02",
    title: "IndexNow & Search Verification Integration",
    type: "improved",
    description: "Integrated automated IndexNow submission script and enhanced search engine verification tags for faster tool indexing.",
    highlights: [
      "Instant IndexNow ping to Bing and Yandex",
      "Dynamic XML sitemap auto-sync with tool registry",
    ],
  },
  {
    id: "2025-04-25-batch-4-tools",
    date: "2025-04-25",
    title: "15 New Format Converters & Media Utilities",
    type: "added",
    description: "Reaching 53 total tools with rich client-side converters and utilities.",
    highlights: [
      "CSS Tools: Glassmorphism Generator, Neumorphism Generator, Box Shadow Builder",
      "Audio/Video: BPM Tap Tempo, Audio Visualizer, Voice Recorder",
      "Data: YAML to JSON, JSON to CSV, Regex Tester & Debugger",
    ],
  },
  {
    id: "2025-04-18-ui-improvements",
    date: "2025-04-18",
    title: "Responsive Layout & Dark Terminal Optimizations",
    type: "improved",
    description: "Optimized mobile drawer navigation, quick switcher keyboard shortcuts (Cmd/Ctrl + K), and UI space efficiency.",
    highlights: [
      "Enhanced OpenGraph previewer 2-column layout",
      "Instant tool search with keyboard arrow navigation",
      "Zero server latency - 100% client-side privacy architecture",
    ],
  },
];
