export interface ToolInfo {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  emoji: string;
  href: string;
  tech: string;
  steps: string[];
  tips: string[];
  example?: { input: string; output: string };
}

export const TOOLS: ToolInfo[] = [
  {
    id: "qrcode",
    title: "QR Code Generator",
    shortTitle: "QR",
    description: "Generate QR codes from text, URLs, or any data. Download as PNG instantly.",
    emoji: "📱",
    href: "/qrcode",
    tech: "Canvas API",
    steps: ["Enter text or URL in the input field", "QR code generates automatically", "Click Download PNG to save"],
    tips: ["Use short URLs for cleaner QR codes", "Test with your phone camera before printing", "High contrast black-and-white scans best"],
    example: { input: "https://example.com", output: "[QR Code Image]" },
  },
  {
    id: "json-formatter",
    title: "JSON Formatter",
    shortTitle: "JSON",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    emoji: "📋",
    href: "/json-formatter",
    tech: "Native JSON API",
    steps: ["Paste your JSON into the editor", "Click Format to prettify or Minify to compact", "Use Validate to check for errors"],
    tips: ["Minify before sending to APIs to reduce payload size", "Always validate JSON before parsing in production", "Use pretty-print for debugging, minify for deployment"],
    example: { input: '{"name":"John","age":30}', output: '{\n  "name": "John",\n  "age": 30\n}' },
  },
  {
    id: "password-generator",
    title: "Password Generator",
    shortTitle: "Password",
    description: "Create strong, random passwords with custom length and character sets.",
    emoji: "🔐",
    href: "/password-generator",
    tech: "Crypto API",
    steps: ["Set password length using the slider", "Choose character types (uppercase, lowercase, numbers, symbols)", "Click Generate Password"],
    tips: ["Use at least 16 characters for maximum security", "Include symbols for better entropy", "Never reuse passwords across different sites"],
    example: { input: "Length: 16, All types", output: "Tq8#kL2$pW9&mN4!" },
  },
  {
    id: "uuid-generator",
    title: "UUID Generator",
    shortTitle: "UUID",
    description: "Generate UUID v4 identifiers instantly. One click to copy.",
    emoji: "🆔",
    href: "/uuid-generator",
    tech: "Crypto API",
    steps: ["Click Generate to create a new UUID v4", "Click Copy to copy to clipboard", "Generate as many as you need"],
    tips: ["UUID v4 uses crypto.randomUUID() for true randomness", "128-bit unique — practically impossible to collide", "Use for database keys, session IDs, or file names"],
    example: { input: "Generate", output: "550e8400-e29b-41d4-a716-446655440000" },
  },
  {
    id: "base64",
    title: "Base64 Encode/Decode",
    shortTitle: "Base64",
    description: "Encode text to Base64 or decode Base64 back to readable text.",
    emoji: "🔡",
    href: "/base64",
    tech: "Native Text API",
    steps: ["Select Encode or Decode mode", "Enter your text or Base64 string", "Click Convert and copy the result"],
    tips: ["Great for embedding small images in HTML/CSS", "Base64 is NOT encryption — anyone can decode it", "Use URL-safe Base64 for web parameters"],
    example: { input: "Hello World", output: "SGVsbG8gV29ybGQ=" },
  },
  {
    id: "markdown-preview",
    title: "Markdown Preview",
    shortTitle: "Markdown",
    description: "Write Markdown and see the rendered HTML preview side by side. Supports both .md and .mdx formats.",
    emoji: "📝",
    href: "/markdown-preview",
    tech: "MDX + Native Parser",
    steps: ["Select .md (Markdown) or .mdx (MDX) mode", "Write content in the left editor", "See live preview update on the right"],
    tips: ["MDX lets you use JSX components in Markdown", "Use .md mode for standard Markdown", "MDX supports JavaScript expressions with {variable}"],
    example: { input: "# Hello\n\n**Bold** text", output: "[Rendered HTML with H1 and bold]" },
  },
  {
    id: "image-compressor",
    title: "Image Compressor",
    shortTitle: "Image",
    description: "Compress images right in your browser. No uploads, no servers.",
    emoji: "🖼️",
    href: "/image-compressor",
    tech: "Canvas API",
    steps: ["Drag & drop or click to upload an image", "Adjust quality with the slider", "Download the compressed image"],
    tips: ["80% quality is the sweet spot for most photos", "Use JPG for photos, PNG for graphics with transparency", "Large images are auto-resized to max 1920px"],
  },
  {
    id: "text-diff",
    title: "Text Diff Checker",
    shortTitle: "Diff",
    description: "Compare two texts and see the differences highlighted line by line.",
    emoji: "🔍",
    href: "/text-diff",
    tech: "LCS Algorithm",
    steps: ["Paste the original text on the left", "Paste the modified text on the right", "Click Compare to see the diff"],
    tips: ["Great for code reviews and document comparison", "Watch out for whitespace-only changes", "Use Copy to get the diff output"],
    example: { input: "hello", output: "hello world (+added)" },
  },
  {
    id: "hash-generator",
    title: "Hash Generator",
    shortTitle: "Hash",
    description: "Compute SHA-1, SHA-256, SHA-384, SHA-512 hashes from text instantly.",
    emoji: "#️⃣",
    href: "/hash-generator",
    tech: "Web Crypto API",
    steps: ["Type or paste text in the input field", "All four SHA digests compute automatically", "Click copy next to a hash to grab it"],
    tips: ["SHA-256 is the current standard for integrity checks", "Hashing is one-way — digests cannot be reversed", "Use hashes to verify downloads and detect changes"],
    example: { input: "hello", output: "2cf24dba5fb0a30e26e83b2ac5b9e29e..." },
  },
  {
    id: "jwt-decoder",
    title: "JWT Decoder",
    shortTitle: "JWT",
    description: "Decode JWT header and payload, inspect claims, and check expiry — locally.",
    emoji: "🗝️",
    href: "/jwt-decoder",
    tech: "Native Text API",
    steps: ["Paste your JWT token into the input field", "Header and payload decode automatically", "Check the exp badge to see if the token is expired"],
    tips: ["Decoding is not verification — signatures need your secret key", "Never paste production tokens into untrusted websites", "Look for exp, iat, and iss claims when debugging auth"],
    example: { input: "eyJhbGciOi...", output: '{"alg":"HS256","typ":"JWT"}' },
  },
  {
    id: "regex-tester",
    title: "Regex Tester",
    shortTitle: "Regex",
    description: "Test regular expressions live with match highlighting and capture groups.",
    emoji: "⁂",
    href: "/regex-tester",
    tech: "Native RegExp API",
    steps: ["Enter a regex pattern and toggle flags", "Type test text below it", "Matches highlight instantly with capture groups listed"],
    tips: ["Use the g flag to find all matches, not just the first", "Non-capturing groups (?:...) keep results clean", "The u flag enables proper unicode handling"],
    example: { input: "\\d+ and g flag", output: "'abc 123 def 456' → matches 123, 456" },
  },
  {
    id: "aes-crypto",
    title: "AES Encrypt/Decrypt",
    shortTitle: "AES",
    description: "Encrypt or decrypt text with a passphrase using AES-GCM. Keys never leave your device.",
    emoji: "🛡️",
    href: "/aes-crypto",
    tech: "Web Crypto API",
    steps: ["Choose Encrypt or Decrypt mode", "Enter a passphrase and your text", "Copy the ciphertext or recovered plaintext"],
    tips: ["AES-256-GCM with PBKDF2 (150k iterations) derives the key", "Lose the passphrase and the data is unrecoverable", "Ciphertext format: base64(iv):base64(data)"],
    example: { input: '"hello" + passphrase', output: "kJ8fW2xR...:9mQzT1vA..." },
  },
  {
    id: "timestamp-converter",
    title: "Timestamp Converter",
    shortTitle: "Timestamp",
    description: "Convert Unix timestamps to dates and back, with relative time and live epoch.",
    emoji: "⏱️",
    href: "/timestamp-converter",
    tech: "Date / Intl API",
    steps: ["Paste a unix timestamp (seconds or ms auto-detected)", "Or pick a date to get its epoch value", "Watch the live 'now' ticker for current epoch"],
    tips: ["Timestamps above 1e11 are treated as milliseconds", "ISO 8601 output is always UTC", "Relative time helps when reading logs"],
    example: { input: "1700000000", output: "2023-11-14T22:13:20Z" },
  },
  {
    id: "url-encoder",
    title: "URL Encoder/Decoder",
    shortTitle: "URL",
    description: "Encode or decode URLs and query parameters safely. Component or full URI mode.",
    emoji: "🔗",
    href: "/url-encoder",
    tech: "Native Text API",
    steps: ["Select Encode or Decode mode", "Choose component or full URI encoding", "Paste text and copy the converted result"],
    tips: ["Use component mode for query parameter values", "encodeURI keeps ://?& intact; encodeURIComponent escapes them", "Spaces become %20 in component mode"],
    example: { input: "hello world&a=1", output: "hello%20world%26a%3D1" },
  },
  {
    id: "chmod-calculator",
    title: "Chmod Calculator",
    shortTitle: "Chmod",
    description: "Compute file permissions from checkboxes or octal. Symbolic and numeric output.",
    emoji: "🔧",
    href: "/chmod-calculator",
    tech: "Bitwise Logic",
    steps: ["Toggle Read/Write/Execute per owner, group, public", "Or type an octal like 755 to sync checkboxes", "Copy either notation for your terminal"],
    tips: ["755 = rwxr-xr-x, common for scripts and directories", "644 = rw-r--r--, common for config files", "Avoid 777 — world-writable files are a security risk"],
    example: { input: "owner: rwx, group: r-x, public: r-x", output: "755 → rwxr-xr-x" },
  },
  {
    id: "cidr-calculator",
    title: "CIDR Calculator",
    shortTitle: "CIDR",
    description: "IPv4 subnet calculator: network, broadcast, netmask, host range from CIDR notation.",
    emoji: "🌐",
    href: "/cidr-calculator",
    tech: "Pure Math",
    steps: ["Enter an address in CIDR form like 192.168.1.0/24", "All subnet values compute instantly", "Copy any result row you need"],
    tips: ["/24 gives 256 addresses, 254 usable hosts", "RFC1918 private ranges: 10/8, 172.16/12, 192.168/16", "/31 and /32 have special host counts per RFC 3021"],
    example: { input: "10.0.0.0/8", output: "network 10.0.0.0 · hosts 16777214" },
  },
  {
    id: "text-transformer",
    title: "Text Transformer",
    shortTitle: "Text Case",
    description: "Convert text case (camel, snake, kebab...) and encode/decode HTML entities.",
    emoji: "Aa",
    href: "/text-transformer",
    tech: "String Ops",
    steps: ["Paste your text in the input area", "Click any case transform or entity button", "Copy the transformed output"],
    tips: ["camelCase and snake_case are one click away", "Entity encode prevents HTML injection in snippets", "Sentence case fixes ALL CAPS text fast"],
    example: { input: "hello world example", output: "helloWorldExample" },
  },
  {
    id: "qr-scanner",
    title: "QR Scanner",
    shortTitle: "QR Scan",
    description: "Decode QR codes from image files right in your browser. No uploads.",
    emoji: "📷",
    href: "/qr-scanner",
    tech: "BarcodeDetector API",
    steps: ["Drop or pick a PNG/JPG/WebP containing a QR code", "Decoded content appears with a copy button", "Links become clickable automatically"],
    tips: ["Requires Chromium-based browsers (Chrome, Edge, Brave)", "Higher contrast images scan more reliably", "Nothing is uploaded — decoding is local"],
    example: { input: "[image with QR]", output: "https://example.com" },
  },
];

export const TOOLS_INFO: Record<string, ToolInfo> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
);

export function getToolInfo(toolId: string): ToolInfo | undefined {
  return TOOLS_INFO[toolId];
}
