export interface ToolInfo {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  emoji: string;
  href: string;
  tech: string;
  steps: string[];
  tips: string[];
  example?: { input: string; output: string };
}

export const TOOLS: ToolInfo[] = [
  {
    id: "qrcode",
    title: "QR Code Generator",
    shortTitle: "QR",
    description: "Generate QR codes from text, URLs, or any data. Download as PNG instantly.",
    emoji: "📱",
    href: "/qrcode",
    tech: "Canvas API",
    steps: ["Enter text or URL in the input field", "QR code generates automatically", "Click Download PNG to save"],
    tips: ["Use short URLs for cleaner QR codes", "Test with your phone camera before printing", "High contrast black-and-white scans best"],
    example: { input: "https://example.com", output: "[QR Code Image]" },
  },
  {
    id: "json-formatter",
    title: "JSON Formatter",
    shortTitle: "JSON",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    emoji: "📋",
    href: "/json-formatter",
    tech: "Native JSON API",
    steps: ["Paste your JSON into the editor", "Click Format to prettify or Minify to compact", "Use Validate to check for errors"],
    tips: ["Minify before sending to APIs to reduce payload size", "Always validate JSON before parsing in production", "Use pretty-print for debugging, minify for deployment"],
    example: { input: '{"name":"John","age":30}', output: '{\n  "name": "John",\n  "age": 30\n}' },
  },
  {
    id: "password-generator",
    title: "Password Generator",
    shortTitle: "Password",
    description: "Create strong, random passwords with custom length and character sets.",
    emoji: "🔐",
    href: "/password-generator",
    tech: "Crypto API",
    steps: ["Set password length using the slider", "Choose character types (uppercase, lowercase, numbers, symbols)", "Click Generate Password"],
    tips: ["Use at least 16 characters for maximum security", "Include symbols for better entropy", "Never reuse passwords across different sites"],
    example: { input: "Length: 16, All types", output: "Tq8#kL2$pW9&mN4!" },
  },
  {
    id: "uuid-generator",
    title: "UUID Generator",
    shortTitle: "UUID",
    description: "Generate UUID v4 identifiers instantly. One click to copy.",
    emoji: "🆔",
    href: "/uuid-generator",
    tech: "Crypto API",
    steps: ["Click Generate to create a new UUID v4", "Click Copy to copy to clipboard", "Generate as many as you need"],
    tips: ["UUID v4 uses crypto.randomUUID() for true randomness", "128-bit unique — practically impossible to collide", "Use for database keys, session IDs, or file names"],
    example: { input: "Generate", output: "550e8400-e29b-41d4-a716-446655440000" },
  },
  {
    id: "base64",
    title: "Base64 Encode/Decode",
    shortTitle: "Base64",
    description: "Encode text to Base64 or decode Base64 back to readable text.",
    emoji: "🔡",
    href: "/base64",
    tech: "Native Text API",
    steps: ["Select Encode or Decode mode", "Enter your text or Base64 string", "Click Convert and copy the result"],
    tips: ["Great for embedding small images in HTML/CSS", "Base64 is NOT encryption — anyone can decode it", "Use URL-safe Base64 for web parameters"],
    example: { input: "Hello World", output: "SGVsbG8gV29ybGQ=" },
  },
  {
    id: "markdown-preview",
    title: "Markdown Preview",
    shortTitle: "Markdown",
    description: "Write Markdown and see the rendered HTML preview side by side. Supports both .md and .mdx formats.",
    emoji: "📝",
    href: "/markdown-preview",
    tech: "MDX + Native Parser",
    steps: ["Select .md (Markdown) or .mdx (MDX) mode", "Write content in the left editor", "See live preview update on the right"],
    tips: ["MDX lets you use JSX components in Markdown", "Use .md mode for standard Markdown", "MDX supports JavaScript expressions with {variable}"],
    example: { input: "# Hello\n\n**Bold** text", output: "[Rendered HTML with H1 and bold]" },
  },
  {
    id: "image-compressor",
    title: "Image Compressor",
    shortTitle: "Image",
    description: "Compress images right in your browser. No uploads, no servers.",
    emoji: "🖼️",
    href: "/image-compressor",
    tech: "Canvas API",
    steps: ["Drag & drop or click to upload an image", "Adjust quality with the slider", "Download the compressed image"],
    tips: ["80% quality is the sweet spot for most photos", "Use JPG for photos, PNG for graphics with transparency", "Large images are auto-resized to max 1920px"],
  },
  {
    id: "text-diff",
    title: "Text Diff Checker",
    shortTitle: "Diff",
    description: "Compare two texts and see the differences highlighted line by line.",
    emoji: "🔍",
    href: "/text-diff",
    tech: "LCS Algorithm",
    steps: ["Paste the original text on the left", "Paste the modified text on the right", "Click Compare to see the diff"],
    tips: ["Great for code reviews and document comparison", "Watch out for whitespace-only changes", "Use Copy to get the diff output"],
    example: { input: "hello", output: "hello world (+added)" },
  },
  {
    id: "hash-generator",
    title: "Hash Generator",
    shortTitle: "Hash",
    description: "Compute SHA-1, SHA-256, SHA-384, SHA-512 hashes from text instantly.",
    emoji: "#️⃣",
    href: "/hash-generator",
    tech: "Web Crypto API",
    steps: ["Type or paste text in the input field", "All four SHA digests compute automatically", "Click copy next to a hash to grab it"],
    tips: ["SHA-256 is the current standard for integrity checks", "Hashing is one-way — digests cannot be reversed", "Use hashes to verify downloads and detect changes"],
    example: { input: "hello", output: "2cf24dba5fb0a30e26e83b2ac5b9e29e..." },
  },
  {
    id: "jwt-decoder",
    title: "JWT Decoder",
    shortTitle: "JWT",
    description: "Decode JWT header and payload, inspect claims, and check expiry — locally.",
    emoji: "🗝️",
    href: "/jwt-decoder",
    tech: "Native Text API",
    steps: ["Paste your JWT token into the input field", "Header and payload decode automatically", "Check the exp badge to see if the token is expired"],
    tips: ["Decoding is not verification — signatures need your secret key", "Never paste production tokens into untrusted websites", "Look for exp, iat, and iss claims when debugging auth"],
    example: { input: "eyJhbGciOi...", output: '{"alg":"HS256","typ":"JWT"}' },
  },
  {
    id: "regex-tester",
    title: "Regex Tester",
    shortTitle: "Regex",
    description: "Test regular expressions live with match highlighting and capture groups.",
    emoji: "⁂",
    href: "/regex-tester",
    tech: "Native RegExp API",
    steps: ["Enter a regex pattern and toggle flags", "Type test text below it", "Matches highlight instantly with capture groups listed"],
    tips: ["Use the g flag to find all matches, not just the first", "Non-capturing groups (?:...) keep results clean", "The u flag enables proper unicode handling"],
    example: { input: "\\d+ and g flag", output: "'abc 123 def 456' → matches 123, 456" },
  },
  {
    id: "aes-crypto",
    title: "AES Encrypt/Decrypt",
    shortTitle: "AES",
    description: "Encrypt or decrypt text with a passphrase using AES-GCM. Keys never leave your device.",
    emoji: "🛡️",
    href: "/aes-crypto",
    tech: "Web Crypto API",
    steps: ["Choose Encrypt or Decrypt mode", "Enter a passphrase and your text", "Copy the ciphertext or recovered plaintext"],
    tips: ["AES-256-GCM with PBKDF2 (150k iterations) derives the key", "Lose the passphrase and the data is unrecoverable", "Ciphertext format: base64(iv):base64(data)"],
    example: { input: '"hello" + passphrase', output: "kJ8fW2xR...:9mQzT1vA..." },
  },
  {
    id: "timestamp-converter",
    title: "Timestamp Converter",
    shortTitle: "Timestamp",
    description: "Convert Unix timestamps to dates and back, with relative time and live epoch.",
    emoji: "⏱️",
    href: "/timestamp-converter",
    tech: "Date / Intl API",
    steps: ["Paste a unix timestamp (seconds or ms auto-detected)", "Or pick a date to get its epoch value", "Watch the live 'now' ticker for current epoch"],
    tips: ["Timestamps above 1e11 are treated as milliseconds", "ISO 8601 output is always UTC", "Relative time helps when reading logs"],
    example: { input: "1700000000", output: "2023-11-14T22:13:20Z" },
  },
  {
    id: "url-encoder",
    title: "URL Encoder/Decoder",
    shortTitle: "URL",
    description: "Encode or decode URLs and query parameters safely. Component or full URI mode.",
    emoji: "🔗",
    href: "/url-encoder",
    tech: "Native Text API",
    steps: ["Select Encode or Decode mode", "Choose component or full URI encoding", "Paste text and copy the converted result"],
    tips: ["Use component mode for query parameter values", "encodeURI keeps ://?& intact; encodeURIComponent escapes them", "Spaces become %20 in component mode"],
    example: { input: "hello world&a=1", output: "hello%20world%26a%3D1" },
  },
  {
    id: "chmod-calculator",
    title: "Chmod Calculator",
    shortTitle: "Chmod",
    description: "Compute file permissions from checkboxes or octal. Symbolic and numeric output.",
    emoji: "🔧",
    href: "/chmod-calculator",
    tech: "Bitwise Logic",
    steps: ["Toggle Read/Write/Execute per owner, group, public", "Or type an octal like 755 to sync checkboxes", "Copy either notation for your terminal"],
    tips: ["755 = rwxr-xr-x, common for scripts and directories", "644 = rw-r--r--, common for config files", "Avoid 777 — world-writable files are a security risk"],
    example: { input: "owner: rwx, group: r-x, public: r-x", output: "755 → rwxr-xr-x" },
  },
  {
    id: "cidr-calculator",
    title: "CIDR Calculator",
    shortTitle: "CIDR",
    description: "IPv4 subnet calculator: network, broadcast, netmask, host range from CIDR notation.",
    emoji: "🌐",
    href: "/cidr-calculator",
    tech: "Pure Math",
    steps: ["Enter an address in CIDR form like 192.168.1.0/24", "All subnet values compute instantly", "Copy any result row you need"],
    tips: ["/24 gives 256 addresses, 254 usable hosts", "RFC1918 private ranges: 10/8, 172.16/12, 192.168/16", "/31 and /32 have special host counts per RFC 3021"],
    example: { input: "10.0.0.0/8", output: "network 10.0.0.0 · hosts 16777214" },
  },
  {
    id: "text-transformer",
    title: "Text Transformer",
    shortTitle: "Text Case",
    description: "Convert text case (camel, snake, kebab...) and encode/decode HTML entities.",
    emoji: "Aa",
    href: "/text-transformer",
    tech: "String Ops",
    steps: ["Paste your text in the input area", "Click any case transform or entity button", "Copy the transformed output"],
    tips: ["camelCase and snake_case are one click away", "Entity encode prevents HTML injection in snippets", "Sentence case fixes ALL CAPS text fast"],
    example: { input: "hello world example", output: "helloWorldExample" },
  },
  {
    id: "qr-scanner",
    title: "QR Scanner",
    shortTitle: "QR Scan",
    description: "Decode QR codes from image files right in your browser. No uploads.",
    emoji: "📷",
    href: "/qr-scanner",
    tech: "BarcodeDetector API",
    steps: ["Drop or pick a PNG/JPG/WebP containing a QR code", "Decoded content appears with a copy button", "Links become clickable automatically"],
    tips: ["Requires Chromium-based browsers (Chrome, Edge, Brave)", "Higher contrast images scan more reliably", "Nothing is uploaded — decoding is local"],
    example: { input: "[image with QR]", output: "https://example.com" },
  },
  {
    id: "pdf-merge",
    title: "Merge PDF",
    shortTitle: "PDF Merge",
    description: "Combine multiple PDF documents into a single file in your browser.",
    emoji: "📑",
    href: "/pdf-merge",
    tech: "pdf-lib",
    steps: ["Upload or drop multiple PDF files", "Reorder or remove files as needed", "Click Merge PDFs to download"],
    tips: ["All processing runs client-side — your documents are never uploaded", "Reorder files to control the page sequence in the output", "Supports encrypted PDFs if no owner password is required"],
    example: { input: "file1.pdf (3 pages) + file2.pdf (2 pages)", output: "merged.pdf (5 pages)" },
  },
  {
    id: "pdf-split",
    title: "Split PDF",
    shortTitle: "PDF Split",
    description: "Extract specific pages or page ranges from a PDF document.",
    emoji: "✂️",
    href: "/pdf-split",
    tech: "pdf-lib",
    steps: ["Upload your PDF document", "Enter page ranges to extract (e.g. 1-3, 5, 8-10)", "Download the extracted PDF"],
    tips: ["Use commas and dashes to define custom ranges like 1-2, 4-6", "Enter single page numbers to extract standalone pages", "Page numbering starts at 1"],
    example: { input: "document.pdf (10 pages) -> Range: 1-3, 5", output: "split.pdf (4 pages)" },
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    shortTitle: "Img to PDF",
    description: "Convert photos and images (PNG, JPG, WebP) into a multi-page PDF document.",
    emoji: "🖼️",
    href: "/image-to-pdf",
    tech: "pdf-lib",
    steps: ["Upload multiple images in your preferred order", "Select page orientation and margins", "Click Convert to generate PDF"],
    tips: ["Reorder images to adjust which photo appears on each page", "Auto-orientation adapts to landscape or portrait photos", "All image resizing and embedding happens in-memory"],
    example: { input: "page1.png, page2.jpg", output: "images.pdf (2 pages)" },
  },
  {
    id: "image-converter",
    title: "Image Converter",
    shortTitle: "Img Convert",
    description: "Convert image files between PNG, JPG, and WebP formats with quality control.",
    emoji: "🔄",
    href: "/image-converter",
    tech: "Canvas API",
    steps: ["Drop or select an image file", "Choose target format (PNG, JPG, WebP)", "Adjust quality slider if needed and download"],
    tips: ["WebP provides superior compression while retaining high clarity", "PNG preserves transparency and is lossless", "JPG is ideal for photos without alpha transparency"],
    example: { input: "photo.png (4.2 MB) -> WebP 85%", output: "photo.webp (680 KB)" },
  },
  {
    id: "exif-stripper",
    title: "EXIF & Metadata Stripper",
    shortTitle: "EXIF Strip",
    description: "Remove GPS coordinates, camera models, and private metadata from photos.",
    emoji: "🛡️",
    href: "/exif-stripper",
    tech: "Canvas API",
    steps: ["Select an image with potential EXIF/GPS tags", "Canvas sanitizes the image by re-encoding pixel data", "Download the privacy-safe clean image"],
    tips: ["Modern smartphone photos embed precise GPS location tags", "Re-encoding via HTML5 Canvas strips all EXIF, IPTC, and XMP metadata", "Use this before sharing photos publicly or uploading to forums"],
    example: { input: "camera_photo.jpg (with GPS)", output: "sanitized_photo.jpg (0 metadata)" },
  },
  {
    id: "steganography",
    title: "Image Steganography",
    shortTitle: "Steganography",
    description: "Hide secret encrypted text inside image pixels using LSB encoding, or extract it.",
    emoji: "🕵️",
    href: "/steganography",
    tech: "Canvas LSB",
    steps: ["Encode mode: choose cover image and write secret message", "Download stego PNG with embedded message", "Decode mode: upload PNG to reveal hidden message"],
    tips: ["Uses Least Significant Bit (LSB) encoding in RGB channels", "Always save/share as PNG — JPG compression destroys hidden bits", "Higher resolution images can hold much larger text payloads"],
    example: { input: "cover.png + 'Secret Message'", output: "stego.png -> Decodes to 'Secret Message'" },
  },
  {
    id: "csv-json",
    title: "CSV ↔ JSON Converter",
    shortTitle: "CSV/JSON",
    description: "Bidirectional converter between CSV tables and JSON arrays with auto-delimiter detection.",
    emoji: "📊",
    href: "/csv-json",
    tech: "Native Parser",
    steps: ["Select CSV to JSON or JSON to CSV mode", "Paste raw text or upload file", "Copy result or download formatted file"],
    tips: ["Auto-detects comma, semicolon, and tab delimiters", "Supports quoted cells containing commas and escaped characters", "Choose between array of objects or 2D array representation"],
    example: { input: "name,age\nAlice,30", output: '[{"name":"Alice","age":30}]' },
  },
  {
    id: "yaml-json",
    title: "YAML ↔ JSON Converter",
    shortTitle: "YAML/JSON",
    description: "Convert between YAML and JSON formats with live validation and line-number error reporting.",
    emoji: "⚙️",
    href: "/yaml-json",
    tech: "js-yaml",
    steps: ["Choose YAML to JSON or JSON to YAML mode", "Paste your configuration data", "Inspect syntax and copy converted output"],
    tips: ["Essential for Kubernetes, Docker Compose, and CI/CD pipelines", "Displays precise error line and column numbers on syntax failures", "Customize JSON indentation (2 spaces, 4 spaces, minified)"],
    example: { input: "name: megatools\nversion: 1", output: '{\n  "name": "megatools",\n  "version": 1\n}' },
  },
  {
    id: "favicon-generator",
    title: "Favicon & Icon Generator",
    shortTitle: "Favicon",
    description: "Generate standard web and app icon sizes (16, 32, 48, 180, 192, 512px) with HTML snippet.",
    emoji: "⭐",
    href: "/favicon-generator",
    tech: "Canvas API",
    steps: ["Upload a square or logo image", "Preview generated sizes with pixel-perfect downscaling", "Download individual sizes and copy <link> HTML tags"],
    tips: ["Start with high-resolution images (at least 512x512 px) for best quality", "Includes Apple Touch Icon (180x180) and Android PWA icons (192, 512)", "Ready-to-use HTML code snippets included for your <head>"],
    example: { input: "logo.png (512x512)", output: "16x16, 32x32, 180x180, 192x192, 512x512 PNGs" },
  },
  {
    id: "file-checksum",
    title: "Large File Hasher",
    shortTitle: "Checksum",
    description: "Calculate SHA-256, SHA-512, SHA-384, and SHA-1 checksums for large files with chunking.",
    emoji: "📦",
    href: "/file-checksum",
    tech: "Web Crypto",
    steps: ["Select or drop any file of any size (even multi-GB)", "Progress bar tracks real-time chunked hashing", "Paste expected checksum to verify file integrity"],
    tips: ["Uses stream chunking to process files without exhausting RAM", "Never uploads files — all hashing is 100% in-browser", "Verification highlight turns green on match and red on mismatch"],
    example: { input: "ubuntu-24.04.iso (4.5 GB)", output: "SHA-256: 2cf24dba5fb... [VERIFIED MATCH]" },
  },
  {
    id: "security-headers",
    title: "Security Headers Generator",
    shortTitle: "Headers",
    description: "Generate hardened HTTP security headers (CSP, HSTS, CORS, X-Frame-Options) for Nginx, Vercel, Apache.",
    emoji: "🛡️",
    href: "/security-headers",
    tech: "Config Generator",
    steps: ["Select security preset (Strict, Recommended, Relaxed) or customize headers", "Pick your web server / platform format (Nginx, Vercel, Apache, Caddy, Cloudflare)", "Click Copy to paste directly into your server configuration"],
    tips: ["Content-Security-Policy (CSP) prevents Cross-Site Scripting (XSS) attacks", "HSTS enforces HTTPS connections and blocks downgrade attacks", "X-Frame-Options DENY blocks clickjacking attempts completely"],
    example: { input: "Preset: Recommended -> Nginx", output: "add_header X-Frame-Options \"DENY\" always;\nadd_header X-Content-Type-Options \"nosniff\" always;" },
  },
  {
    id: "port-lookup",
    title: "Common Ports Reference",
    shortTitle: "Ports",
    description: "Database of standard & security-sensitive TCP/UDP ports with service info and vulnerability risk notes.",
    emoji: "🔌",
    href: "/port-lookup",
    tech: "Port Database",
    steps: ["Search by port number (e.g. 22, 443, 3306) or service name (ssh, mysql, redis)", "Filter by protocol (TCP/UDP) or security risk level (Critical, Warning, Safe)", "Review risk notes and standard mitigations for open ports"],
    tips: ["Never expose databases (MySQL 3306, Redis 6379, Postgres 5432) directly to the public internet", "Port 445 (SMB) is a major vector for ransomware (EternalBlue)", "Always change default SSH port 22 or enforce public key authentication"],
    example: { input: "Port 22", output: "SSH (Secure Shell) · TCP · Safe when hardened with public keys" },
  },
  {
    id: "binary-converter",
    title: "Binary & Base Converter",
    shortTitle: "Base Convert",
    description: "Convert text and numbers between Binary, Hex, Base32, Base58 (Bitcoin/Solana), and Decimal.",
    emoji: "0️⃣",
    href: "/binary-converter",
    tech: "Bitwise Math",
    steps: ["Type text or paste encoded numbers in any field", "All representations (Binary, Hex, Base58, Base32, Decimal) sync in real time", "Click copy next to any format"],
    tips: ["Base58 avoids ambiguous characters (0, O, I, l) and is used in Bitcoin and Solana addresses", "Hexadecimal (Base16) is standard for memory dumps, hashes, and color codes", "Binary bit streams show exact 8-bit UTF-8 byte sequences"],
    example: { input: "MegaTools", output: "Hex: 4d656761546f6f6c73 · Base58: 4z9v78VbX4n" },
  },
  {
    id: "cert-inspector",
    title: "SSL / X.509 Certificate Inspector",
    shortTitle: "Cert Inspect",
    description: "Parse and inspect X.509 certificates and CSRs (PEM format) locally without sending keys anywhere.",
    emoji: "📜",
    href: "/cert-inspector",
    tech: "ASN.1 Parser",
    steps: ["Paste public certificate (.pem / .crt) or CSR block", "Parser extracts Common Name, Subject Alternative Names (SAN), Validity, and Issuer", "Check expiry warnings and public key strength"],
    tips: ["Everything parses client-side — your certificates and public keys are never uploaded", "Inspect SANs to see all domains covered by a single wildcard or multi-domain cert", "Check validity dates to prevent unexpected production SSL outages"],
    example: { input: "-----BEGIN CERTIFICATE-----\nMIIE...", output: "Subject: *.megatools.vercel.app · Valid until: 2027-01-01" },
  },
  {
    id: "sql-formatter",
    title: "SQL Formatter & Beautifier",
    shortTitle: "SQL Format",
    description: "Format, beautify, and indent complex SQL queries in your browser. Supports PostgreSQL, MySQL, SQLite.",
    emoji: "🗄️",
    href: "/sql-formatter",
    tech: "sql-formatter",
    steps: ["Paste messy or minified SQL query into the editor", "Choose SQL dialect and keyword casing (UPPERCASE / lowercase)", "Copy formatted query or download formatted SQL script"],
    tips: ["UPPERCASE keywords make complex JOINs and subqueries much easier to read", "Formatting queries before code reviews helps spot missing WHERE clauses", "Supports standard SQL, PostgreSQL, MySQL, and SQLite dialects"],
    example: { input: "select id,name from users where active=1 and role='admin'", output: "SELECT\n  id,\n  name\nFROM\n  users\nWHERE\n  active = 1\n  AND role = 'admin';" },
  },
  {
    id: "code-minifier",
    title: "HTML & CSS Minifier",
    shortTitle: "Minifier",
    description: "Minify or beautify HTML and CSS code to optimize website load speeds and strip unnecessary bytes.",
    emoji: "⚡",
    href: "/code-minifier",
    tech: "Regex Parser",
    steps: ["Select HTML or CSS tab and choose Minify or Beautify mode", "Paste raw code into the input pane", "Inspect size reduction percentage and copy minified output"],
    tips: ["Minifying removes comments, unnecessary whitespace, and line breaks", "Smaller CSS and HTML files improve Google Lighthouse and First Contentful Paint (FCP)", "Use Beautify mode to unminify compressed code for debugging"],
    example: { input: "body { \n  color: red; \n}", output: "body{color:red;}" },
  },
  {
    id: "color-contrast",
    title: "Color Contrast & Palette",
    shortTitle: "Contrast",
    description: "WCAG 2.1 contrast ratio checker (AA/AAA compliance) with instant HEX, RGB, HSL, and OKLCH conversions.",
    emoji: "🎨",
    href: "/color-contrast",
    tech: "Color Science",
    steps: ["Select or enter Foreground (Text) and Background colors", "Check real-time WCAG 2.1 contrast score (AA / AAA compliance)", "Copy converted values in HEX, RGB, HSL, or OKLCH"],
    tips: ["WCAG AA requires minimum 4.5:1 for normal text and 3.0:1 for large text (18pt+)", "WCAG AAA requires 7.0:1 for highest accessibility compliance", "High contrast improves readability for visually impaired users and under bright sunlight"],
    example: { input: "Text: #4ade80 (Green) on Bg: #0a0f0d (Black)", output: "Contrast Ratio: 13.8:1 [AAA PASS]" },
  },
  {
    id: "svg-optimizer",
    title: "SVG Optimizer & Cleaner",
    shortTitle: "SVG Clean",
    description: "Clean and minify SVG vector files by stripping editor metadata, comments, and unused attributes.",
    emoji: "📐",
    href: "/svg-optimizer",
    tech: "DOM Parser",
    steps: ["Paste SVG XML code or upload an .svg file", "Optimizer strips Illustrator/Inkscape bloat, unused namespaces, and comments", "Preview live vector output and download cleaned .svg"],
    tips: ["Vector editors add hundreds of bytes of useless metadata and editor tags", "Optimized SVGs load faster and can be inlined directly into React/Next.js components", "Lossless optimization preserves path coordinates and visual shapes exactly"],
    example: { input: "<svg ... inkscape:version=\"1.0\">...", output: "Clean SVG with 45% size reduction" },
  },
  {
    id: "screen-recorder",
    title: "Screen & Audio Recorder",
    shortTitle: "Screen Rec",
    description: "Record your screen, browser tab, or app window with microphone audio. 100% private, zero uploads.",
    emoji: "🎥",
    href: "/screen-recorder",
    tech: "MediaRecorder API",
    steps: ["Click Start Recording and select Screen, Window, or Chrome Tab", "Toggle Microphone option to record voice commentary", "Stop recording to preview video and download high-quality .webm"],
    tips: ["Runs entirely in your browser via HTML5 MediaStreams — no third-party recording software needed", "Choose 'Current Tab' with audio sharing to record web demos with system sound", "Recordings are saved directly to your local disk upon completion"],
    example: { input: "Screen + Mic stream", output: "screen-recording-2026.webm" },
  },
  {
    id: "audio-trimmer",
    title: "Audio Trimmer & Cutter",
    shortTitle: "Audio Cut",
    description: "Visual waveform audio cutter for MP3, WAV, and OGG files. Trim audio clips client-side.",
    emoji: "🎵",
    href: "/audio-trimmer",
    tech: "Web Audio API",
    steps: ["Drop or select an audio file (MP3, WAV, OGG, AAC)", "Inspect visual waveform and adjust Start and End time markers", "Preview trimmed segment and click Export to download clean .wav file"],
    tips: ["Decodes audio in-memory using Web Audio API — your music/recordings never leave your device", "Zoom into waveform to trim precise milliseconds", "Exported WAV files are uncompressed and universally compatible"],
    example: { input: "song.mp3 (3:45) -> Range 0:15 - 0:45", output: "trimmed-clip.wav (30s)" },
  },
];

export const TOOLS_INFO: Record<string, ToolInfo> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
);

export function getToolInfo(toolId: string): ToolInfo | undefined {
  return TOOLS_INFO[toolId];
}

export interface ToolCategory {
  id: string;
  name: string;
  emoji: string;
  toolIds: string[];
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: "pdf-docs",
    name: "PDF & Documents",
    emoji: "📄",
    toolIds: ["pdf-merge", "pdf-split", "image-to-pdf"],
  },
  {
    id: "crypto-security",
    name: "Security & Crypto",
    emoji: "🔐",
    toolIds: [
      "password-generator",
      "uuid-generator",
      "hash-generator",
      "aes-crypto",
      "jwt-decoder",
      "file-checksum",
      "steganography",
      "security-headers",
      "cert-inspector",
      "binary-converter",
    ],
  },
  {
    id: "media-qr",
    name: "Media & Audio/Video",
    emoji: "📱",
    toolIds: [
      "qrcode",
      "qr-scanner",
      "image-compressor",
      "image-converter",
      "exif-stripper",
      "favicon-generator",
      "screen-recorder",
      "audio-trimmer",
    ],
  },
  {
    id: "format-text",
    name: "Format & Code",
    emoji: "📝",
    toolIds: [
      "json-formatter",
      "base64",
      "url-encoder",
      "text-diff",
      "text-transformer",
      "markdown-preview",
      "csv-json",
      "yaml-json",
      "sql-formatter",
      "code-minifier",
      "svg-optimizer",
    ],
  },
  {
    id: "dev-network",
    name: "Dev & Network",
    emoji: "⚙️",
    toolIds: [
      "timestamp-converter",
      "regex-tester",
      "chmod-calculator",
      "cidr-calculator",
      "port-lookup",
      "color-contrast",
    ],
  },
];
