export interface ToolInfo {
  id: string;
  title: string;
  shortTitle: string;
  description: string;
  emoji: string;
  href: string;
  tech: string;
  steps: string[];
  tips: string[];
  example?: { input: string; output: string };
}

export const TOOLS: ToolInfo[] = [
  {
    id: "qrcode",
    title: "QR Code Generator",
    shortTitle: "QR",
    description: "Generate QR codes from text, URLs, or any data. Download as PNG instantly.",
    emoji: "📱",
    href: "/qrcode",
    tech: "Canvas API",
    steps: ["Enter text or URL in the input field", "QR code generates automatically", "Click Download PNG to save"],
    tips: ["Use short URLs for cleaner QR codes", "Test with your phone camera before printing", "High contrast black-and-white scans best"],
    example: { input: "https://example.com", output: "[QR Code Image]" },
  },
  {
    id: "json-formatter",
    title: "JSON Formatter",
    shortTitle: "JSON",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    emoji: "📋",
    href: "/json-formatter",
    tech: "Native JSON API",
    steps: ["Paste your JSON into the editor", "Click Format to prettify or Minify to compact", "Use Validate to check for errors"],
    tips: ["Minify before sending to APIs to reduce payload size", "Always validate JSON before parsing in production", "Use pretty-print for debugging, minify for deployment"],
    example: { input: '{"name":"John","age":30}', output: '{\n  "name": "John",\n  "age": 30\n}' },
  },
  {
    id: "password-generator",
    title: "Password Generator",
    shortTitle: "Password",
    description: "Create strong, random passwords with custom length and character sets.",
    emoji: "🔐",
    href: "/password-generator",
    tech: "Crypto API",
    steps: ["Set password length using the slider", "Choose character types (uppercase, lowercase, numbers, symbols)", "Click Generate Password"],
    tips: ["Use at least 16 characters for maximum security", "Include symbols for better entropy", "Never reuse passwords across different sites"],
    example: { input: "Length: 16, All types", output: "Tq8#kL2$pW9&mN4!" },
  },
  {
    id: "uuid-generator",
    title: "UUID Generator",
    shortTitle: "UUID",
    description: "Generate UUID v4 identifiers instantly. One click to copy.",
    emoji: "🆔",
    href: "/uuid-generator",
    tech: "Crypto API",
    steps: ["Click Generate to create a new UUID v4", "Click Copy to copy to clipboard", "Generate as many as you need"],
    tips: ["UUID v4 uses crypto.randomUUID() for true randomness", "128-bit unique — practically impossible to collide", "Use for database keys, session IDs, or file names"],
    example: { input: "Generate", output: "550e8400-e29b-41d4-a716-446655440000" },
  },
  {
    id: "base64",
    title: "Base64 Encode/Decode",
    shortTitle: "Base64",
    description: "Encode text to Base64 or decode Base64 back to readable text.",
    emoji: "🔡",
    href: "/base64",
    tech: "Native Text API",
    steps: ["Select Encode or Decode mode", "Enter your text or Base64 string", "Click Convert and copy the result"],
    tips: ["Great for embedding small images in HTML/CSS", "Base64 is NOT encryption — anyone can decode it", "Use URL-safe Base64 for web parameters"],
    example: { input: "Hello World", output: "SGVsbG8gV29ybGQ=" },
  },
  {
    id: "markdown-preview",
    title: "Markdown Preview",
    shortTitle: "Markdown",
    description: "Write Markdown and see the rendered HTML preview side by side. Supports both .md and .mdx formats.",
    emoji: "📝",
    href: "/markdown-preview",
    tech: "MDX + Native Parser",
    steps: ["Select .md (Markdown) or .mdx (MDX) mode", "Write content in the left editor", "See live preview update on the right"],
    tips: ["MDX lets you use JSX components in Markdown", "Use .md mode for standard Markdown", "MDX supports JavaScript expressions with {variable}"],
    example: { input: "# Hello\n\n**Bold** text", output: "[Rendered HTML with H1 and bold]" },
  },
  {
    id: "image-compressor",
    title: "Image Compressor",
    shortTitle: "Image",
    description: "Compress images right in your browser. No uploads, no servers.",
    emoji: "🖼️",
    href: "/image-compressor",
    tech: "Canvas API",
    steps: ["Drag & drop or click to upload an image", "Adjust quality with the slider", "Download the compressed image"],
    tips: ["80% quality is the sweet spot for most photos", "Use JPG for photos, PNG for graphics with transparency", "Large images are auto-resized to max 1920px"],
  },
  {
    id: "text-diff",
    title: "Text Diff Checker",
    shortTitle: "Diff",
    description: "Compare two texts and see the differences highlighted line by line.",
    emoji: "🔍",
    href: "/text-diff",
    tech: "LCS Algorithm",
    steps: ["Paste the original text on the left", "Paste the modified text on the right", "Click Compare to see the diff"],
    tips: ["Great for code reviews and document comparison", "Watch out for whitespace-only changes", "Use Copy to get the diff output"],
    example: { input: "hello", output: "hello world (+added)" },
  },
  {
    id: "hash-generator",
    title: "Hash Generator",
    shortTitle: "Hash",
    description: "Compute SHA-1, SHA-256, SHA-384, SHA-512 hashes from text instantly.",
    emoji: "#️⃣",
    href: "/hash-generator",
    tech: "Web Crypto API",
    steps: ["Type or paste text in the input field", "All four SHA digests compute automatically", "Click copy next to a hash to grab it"],
    tips: ["SHA-256 is the current standard for integrity checks", "Hashing is one-way — digests cannot be reversed", "Use hashes to verify downloads and detect changes"],
    example: { input: "hello", output: "2cf24dba5fb0a30e26e83b2ac5b9e29e..." },
  },
  {
    id: "jwt-decoder",
    title: "JWT Decoder",
    shortTitle: "JWT",
    description: "Decode JWT header and payload, inspect claims, and check expiry — locally.",
    emoji: "🗝️",
    href: "/jwt-decoder",
    tech: "Native Text API",
    steps: ["Paste your JWT token into the input field", "Header and payload decode automatically", "Check the exp badge to see if the token is expired"],
    tips: ["Decoding is not verification — signatures need your secret key", "Never paste production tokens into untrusted websites", "Look for exp, iat, and iss claims when debugging auth"],
    example: { input: "eyJhbGciOi...", output: '{"alg":"HS256","typ":"JWT"}' },
  },
  {
    id: "regex-tester",
    title: "Regex Tester",
    shortTitle: "Regex",
    description: "Test regular expressions live with match highlighting and capture groups.",
    emoji: "⁂",
    href: "/regex-tester",
    tech: "Native RegExp API",
    steps: ["Enter a regex pattern and toggle flags", "Type test text below it", "Matches highlight instantly with capture groups listed"],
    tips: ["Use the g flag to find all matches, not just the first", "Non-capturing groups (?:...) keep results clean", "The u flag enables proper unicode handling"],
    example: { input: "\\d+ and g flag", output: "'abc 123 def 456' → matches 123, 456" },
  },
  {
    id: "aes-crypto",
    title: "AES Encrypt/Decrypt",
    shortTitle: "AES",
    description: "Encrypt or decrypt text with a passphrase using AES-GCM. Keys never leave your device.",
    emoji: "🛡️",
    href: "/aes-crypto",
    tech: "Web Crypto API",
    steps: ["Choose Encrypt or Decrypt mode", "Enter a passphrase and your text", "Copy the ciphertext or recovered plaintext"],
    tips: ["AES-256-GCM with PBKDF2 (150k iterations) derives the key", "Lose the passphrase and the data is unrecoverable", "Ciphertext format: base64(iv):base64(data)"],
    example: { input: '"hello" + passphrase', output: "kJ8fW2xR...:9mQzT1vA..." },
  },
  {
    id: "timestamp-converter",
    title: "Timestamp Converter",
    shortTitle: "Timestamp",
    description: "Convert Unix timestamps to dates and back, with relative time and live epoch.",
    emoji: "⏱️",
    href: "/timestamp-converter",
    tech: "Date / Intl API",
    steps: ["Paste a unix timestamp (seconds or ms auto-detected)", "Or pick a date to get its epoch value", "Watch the live 'now' ticker for current epoch"],
    tips: ["Timestamps above 1e11 are treated as milliseconds", "ISO 8601 output is always UTC", "Relative time helps when reading logs"],
    example: { input: "1700000000", output: "2023-11-14T22:13:20Z" },
  },
  {
    id: "url-encoder",
    title: "URL Encoder/Decoder",
    shortTitle: "URL",
    description: "Encode or decode URLs and query parameters safely. Component or full URI mode.",
    emoji: "🔗",
    href: "/url-encoder",
    tech: "Native Text API",
    steps: ["Select Encode or Decode mode", "Choose component or full URI encoding", "Paste text and copy the converted result"],
    tips: ["Use component mode for query parameter values", "encodeURI keeps ://?& intact; encodeURIComponent escapes them", "Spaces become %20 in component mode"],
    example: { input: "hello world&a=1", output: "hello%20world%26a%3D1" },
  },
  {
    id: "chmod-calculator",
    title: "Chmod Calculator",
    shortTitle: "Chmod",
    description: "Compute file permissions from checkboxes or octal. Symbolic and numeric output.",
    emoji: "🔧",
    href: "/chmod-calculator",
    tech: "Bitwise Logic",
    steps: ["Toggle Read/Write/Execute per owner, group, public", "Or type an octal like 755 to sync checkboxes", "Copy either notation for your terminal"],
    tips: ["755 = rwxr-xr-x, common for scripts and directories", "644 = rw-r--r--, common for config files", "Avoid 777 — world-writable files are a security risk"],
    example: { input: "owner: rwx, group: r-x, public: r-x", output: "755 → rwxr-xr-x" },
  },
  {
    id: "cidr-calculator",
    title: "CIDR Calculator",
    shortTitle: "CIDR",
    description: "IPv4 subnet calculator: network, broadcast, netmask, host range from CIDR notation.",
    emoji: "🌐",
    href: "/cidr-calculator",
    tech: "Pure Math",
    steps: ["Enter an address in CIDR form like 192.168.1.0/24", "All subnet values compute instantly", "Copy any result row you need"],
    tips: ["/24 gives 256 addresses, 254 usable hosts", "RFC1918 private ranges: 10/8, 172.16/12, 192.168/16", "/31 and /32 have special host counts per RFC 3021"],
    example: { input: "10.0.0.0/8", output: "network 10.0.0.0 · hosts 16777214" },
  },
  {
    id: "text-transformer",
    title: "Text Transformer",
    shortTitle: "Text Case",
    description: "Convert text case (camel, snake, kebab...) and encode/decode HTML entities.",
    emoji: "Aa",
    href: "/text-transformer",
    tech: "String Ops",
    steps: ["Paste your text in the input area", "Click any case transform or entity button", "Copy the transformed output"],
    tips: ["camelCase and snake_case are one click away", "Entity encode prevents HTML injection in snippets", "Sentence case fixes ALL CAPS text fast"],
    example: { input: "hello world example", output: "helloWorldExample" },
  },
  {
    id: "qr-scanner",
    title: "QR Scanner",
    shortTitle: "QR Scan",
    description: "Decode QR codes from image files right in your browser. No uploads.",
    emoji: "📷",
    href: "/qr-scanner",
    tech: "BarcodeDetector API",
    steps: ["Drop or pick a PNG/JPG/WebP containing a QR code", "Decoded content appears with a copy button", "Links become clickable automatically"],
    tips: ["Requires Chromium-based browsers (Chrome, Edge, Brave)", "Higher contrast images scan more reliably", "Nothing is uploaded — decoding is local"],
    example: { input: "[image with QR]", output: "https://example.com" },
  },
  {
    id: "pdf-merge",
    title: "Merge PDF",
    shortTitle: "PDF Merge",
    description: "Combine multiple PDF documents into a single file in your browser.",
    emoji: "📑",
    href: "/pdf-merge",
    tech: "pdf-lib",
    steps: ["Upload or drop multiple PDF files", "Reorder or remove files as needed", "Click Merge PDFs to download"],
    tips: ["All processing runs client-side — your documents are never uploaded", "Reorder files to control the page sequence in the output", "Supports encrypted PDFs if no owner password is required"],
    example: { input: "file1.pdf (3 pages) + file2.pdf (2 pages)", output: "merged.pdf (5 pages)" },
  },
  {
    id: "pdf-split",
    title: "Split PDF",
    shortTitle: "PDF Split",
    description: "Extract specific pages or page ranges from a PDF document.",
    emoji: "✂️",
    href: "/pdf-split",
    tech: "pdf-lib",
    steps: ["Upload your PDF document", "Enter page ranges to extract (e.g. 1-3, 5, 8-10)", "Download the extracted PDF"],
    tips: ["Use commas and dashes to define custom ranges like 1-2, 4-6", "Enter single page numbers to extract standalone pages", "Page numbering starts at 1"],
    example: { input: "document.pdf (10 pages) -> Range: 1-3, 5", output: "split.pdf (4 pages)" },
  },
  {
    id: "image-to-pdf",
    title: "Image to PDF",
    shortTitle: "Img to PDF",
    description: "Convert photos and images (PNG, JPG, WebP) into a multi-page PDF document.",
    emoji: "🖼️",
    href: "/image-to-pdf",
    tech: "pdf-lib",
    steps: ["Upload multiple images in your preferred order", "Select page orientation and margins", "Click Convert to generate PDF"],
    tips: ["Reorder images to adjust which photo appears on each page", "Auto-orientation adapts to landscape or portrait photos", "All image resizing and embedding happens in-memory"],
    example: { input: "page1.png, page2.jpg", output: "images.pdf (2 pages)" },
  },
  {
    id: "image-converter",
    title: "Image Converter",
    shortTitle: "Img Convert",
    description: "Convert image files between PNG, JPG, and WebP formats with quality control.",
    emoji: "🔄",
    href: "/image-converter",
    tech: "Canvas API",
    steps: ["Drop or select an image file", "Choose target format (PNG, JPG, WebP)", "Adjust quality slider if needed and download"],
    tips: ["WebP provides superior compression while retaining high clarity", "PNG preserves transparency and is lossless", "JPG is ideal for photos without alpha transparency"],
    example: { input: "photo.png (4.2 MB) -> WebP 85%", output: "photo.webp (680 KB)" },
  },
  {
    id: "exif-stripper",
    title: "EXIF & Metadata Stripper",
    shortTitle: "EXIF Strip",
    description: "Remove GPS coordinates, camera models, and private metadata from photos.",
    emoji: "🛡️",
    href: "/exif-stripper",
    tech: "Canvas API",
    steps: ["Select an image with potential EXIF/GPS tags", "Canvas sanitizes the image by re-encoding pixel data", "Download the privacy-safe clean image"],
    tips: ["Modern smartphone photos embed precise GPS location tags", "Re-encoding via HTML5 Canvas strips all EXIF, IPTC, and XMP metadata", "Use this before sharing photos publicly or uploading to forums"],
    example: { input: "camera_photo.jpg (with GPS)", output: "sanitized_photo.jpg (0 metadata)" },
  },
  {
    id: "steganography",
    title: "Image Steganography",
    shortTitle: "Steganography",
    description: "Hide secret encrypted text inside image pixels using LSB encoding, or extract it.",
    emoji: "🕵️",
    href: "/steganography",
    tech: "Canvas LSB",
    steps: ["Encode mode: choose cover image and write secret message", "Download stego PNG with embedded message", "Decode mode: upload PNG to reveal hidden message"],
    tips: ["Uses Least Significant Bit (LSB) encoding in RGB channels", "Always save/share as PNG — JPG compression destroys hidden bits", "Higher resolution images can hold much larger text payloads"],
    example: { input: "cover.png + 'Secret Message'", output: "stego.png -> Decodes to 'Secret Message'" },
  },
  {
    id: "csv-json",
    title: "CSV ↔ JSON Converter",
    shortTitle: "CSV/JSON",
    description: "Bidirectional converter between CSV tables and JSON arrays with auto-delimiter detection.",
    emoji: "📊",
    href: "/csv-json",
    tech: "Native Parser",
    steps: ["Select CSV to JSON or JSON to CSV mode", "Paste raw text or upload file", "Copy result or download formatted file"],
    tips: ["Auto-detects comma, semicolon, and tab delimiters", "Supports quoted cells containing commas and escaped characters", "Choose between array of objects or 2D array representation"],
    example: { input: "name,age\nAlice,30", output: '[{"name":"Alice","age":30}]' },
  },
  {
    id: "yaml-json",
    title: "YAML ↔ JSON Converter",
    shortTitle: "YAML/JSON",
    description: "Convert between YAML and JSON formats with live validation and line-number error reporting.",
    emoji: "⚙️",
    href: "/yaml-json",
    tech: "js-yaml",
    steps: ["Choose YAML to JSON or JSON to YAML mode", "Paste your configuration data", "Inspect syntax and copy converted output"],
    tips: ["Essential for Kubernetes, Docker Compose, and CI/CD pipelines", "Displays precise error line and column numbers on syntax failures", "Customize JSON indentation (2 spaces, 4 spaces, minified)"],
    example: { input: "name: megatools\nversion: 1", output: '{\n  "name": "megatools",\n  "version": 1\n}' },
  },
  {
    id: "favicon-generator",
    title: "Favicon & Icon Generator",
    shortTitle: "Favicon",
    description: "Generate standard web and app icon sizes (16, 32, 48, 180, 192, 512px) with HTML snippet.",
    emoji: "⭐",
    href: "/favicon-generator",
    tech: "Canvas API",
    steps: ["Upload a square or logo image", "Preview generated sizes with pixel-perfect downscaling", "Download individual sizes and copy <link> HTML tags"],
    tips: ["Start with high-resolution images (at least 512x512 px) for best quality", "Includes Apple Touch Icon (180x180) and Android PWA icons (192, 512)", "Ready-to-use HTML code snippets included for your <head>"],
    example: { input: "logo.png (512x512)", output: "16x16, 32x32, 180x180, 192x192, 512x512 PNGs" },
  },
  {
    id: "file-checksum",
    title: "Large File Hasher",
    shortTitle: "Checksum",
    description: "Calculate SHA-256, SHA-512, SHA-384, and SHA-1 checksums for large files with chunking.",
    emoji: "📦",
    href: "/file-checksum",
    tech: "Web Crypto",
    steps: ["Select or drop any file of any size (even multi-GB)", "Progress bar tracks real-time chunked hashing", "Paste expected checksum to verify file integrity"],
    tips: ["Uses stream chunking to process files without exhausting RAM", "Never uploads files — all hashing is 100% in-browser", "Verification highlight turns green on match and red on mismatch"],
    example: { input: "ubuntu-24.04.iso (4.5 GB)", output: "SHA-256: 2cf24dba5fb... [VERIFIED MATCH]" },
  },
  {
    id: "security-headers",
    title: "Security Headers Generator",
    shortTitle: "Headers",
    description: "Generate hardened HTTP security headers (CSP, HSTS, CORS, X-Frame-Options) for Nginx, Vercel, Apache.",
    emoji: "🛡️",
    href: "/security-headers",
    tech: "Config Generator",
    steps: ["Select security preset (Strict, Recommended, Relaxed) or customize headers", "Pick your web server / platform format (Nginx, Vercel, Apache, Caddy, Cloudflare)", "Click Copy to paste directly into your server configuration"],
    tips: ["Content-Security-Policy (CSP) prevents Cross-Site Scripting (XSS) attacks", "HSTS enforces HTTPS connections and blocks downgrade attacks", "X-Frame-Options DENY blocks clickjacking attempts completely"],
    example: { input: "Preset: Recommended -> Nginx", output: "add_header X-Frame-Options \"DENY\" always;\nadd_header X-Content-Type-Options \"nosniff\" always;" },
  },
  {
    id: "port-lookup",
    title: "Common Ports Reference",
    shortTitle: "Ports",
    description: "Database of standard & security-sensitive TCP/UDP ports with service info and vulnerability risk notes.",
    emoji: "🔌",
    href: "/port-lookup",
    tech: "Port Database",
    steps: ["Search by port number (e.g. 22, 443, 3306) or service name (ssh, mysql, redis)", "Filter by protocol (TCP/UDP) or security risk level (Critical, Warning, Safe)", "Review risk notes and standard mitigations for open ports"],
    tips: ["Never expose databases (MySQL 3306, Redis 6379, Postgres 5432) directly to the public internet", "Port 445 (SMB) is a major vector for ransomware (EternalBlue)", "Always change default SSH port 22 or enforce public key authentication"],
    example: { input: "Port 22", output: "SSH (Secure Shell) · TCP · Safe when hardened with public keys" },
  },
  {
    id: "binary-converter",
    title: "Binary & Base Converter",
    shortTitle: "Base Convert",
    description: "Convert text and numbers between Binary, Hex, Base32, Base58 (Bitcoin/Solana), and Decimal.",
    emoji: "0️⃣",
    href: "/binary-converter",
    tech: "Bitwise Math",
    steps: ["Type text or paste encoded numbers in any field", "All representations (Binary, Hex, Base58, Base32, Decimal) sync in real time", "Click copy next to any format"],
    tips: ["Base58 avoids ambiguous characters (0, O, I, l) and is used in Bitcoin and Solana addresses", "Hexadecimal (Base16) is standard for memory dumps, hashes, and color codes", "Binary bit streams show exact 8-bit UTF-8 byte sequences"],
    example: { input: "MegaTools", output: "Hex: 4d656761546f6f6c73 · Base58: 4z9v78VbX4n" },
  },
  {
    id: "cert-inspector",
    title: "SSL / X.509 Certificate Inspector",
    shortTitle: "Cert Inspect",
    description: "Parse and inspect X.509 certificates and CSRs (PEM format) locally without sending keys anywhere.",
    emoji: "📜",
    href: "/cert-inspector",
    tech: "ASN.1 Parser",
    steps: ["Paste public certificate (.pem / .crt) or CSR block", "Parser extracts Common Name, Subject Alternative Names (SAN), Validity, and Issuer", "Check expiry warnings and public key strength"],
    tips: ["Everything parses client-side — your certificates and public keys are never uploaded", "Inspect SANs to see all domains covered by a single wildcard or multi-domain cert", "Check validity dates to prevent unexpected production SSL outages"],
    example: { input: "-----BEGIN CERTIFICATE-----\nMIIE...", output: "Subject: *.megatools-tau.vercel.app · Valid until: 2027-01-01" },
  },
  {
    id: "sql-formatter",
    title: "SQL Formatter & Beautifier",
    shortTitle: "SQL Format",
    description: "Format, beautify, and indent complex SQL queries in your browser. Supports PostgreSQL, MySQL, SQLite.",
    emoji: "🗄️",
    href: "/sql-formatter",
    tech: "sql-formatter",
    steps: ["Paste messy or minified SQL query into the editor", "Choose SQL dialect and keyword casing (UPPERCASE / lowercase)", "Copy formatted query or download formatted SQL script"],
    tips: ["UPPERCASE keywords make complex JOINs and subqueries much easier to read", "Formatting queries before code reviews helps spot missing WHERE clauses", "Supports standard SQL, PostgreSQL, MySQL, and SQLite dialects"],
    example: { input: "select id,name from users where active=1 and role='admin'", output: "SELECT\n  id,\n  name\nFROM\n  users\nWHERE\n  active = 1\n  AND role = 'admin';" },
  },
  {
    id: "code-minifier",
    title: "HTML & CSS Minifier",
    shortTitle: "Minifier",
    description: "Minify or beautify HTML and CSS code to optimize website load speeds and strip unnecessary bytes.",
    emoji: "⚡",
    href: "/code-minifier",
    tech: "Regex Parser",
    steps: ["Select HTML or CSS tab and choose Minify or Beautify mode", "Paste raw code into the input pane", "Inspect size reduction percentage and copy minified output"],
    tips: ["Minifying removes comments, unnecessary whitespace, and line breaks", "Smaller CSS and HTML files improve Google Lighthouse and First Contentful Paint (FCP)", "Use Beautify mode to unminify compressed code for debugging"],
    example: { input: "body { \n  color: red; \n}", output: "body{color:red;}" },
  },
  {
    id: "color-contrast",
    title: "Color Contrast & Palette",
    shortTitle: "Contrast",
    description: "WCAG 2.1 contrast ratio checker (AA/AAA compliance) with instant HEX, RGB, HSL, and OKLCH conversions.",
    emoji: "🎨",
    href: "/color-contrast",
    tech: "Color Science",
    steps: ["Select or enter Foreground (Text) and Background colors", "Check real-time WCAG 2.1 contrast score (AA / AAA compliance)", "Copy converted values in HEX, RGB, HSL, or OKLCH"],
    tips: ["WCAG AA requires minimum 4.5:1 for normal text and 3.0:1 for large text (18pt+)", "WCAG AAA requires 7.0:1 for highest accessibility compliance", "High contrast improves readability for visually impaired users and under bright sunlight"],
    example: { input: "Text: #4ade80 (Green) on Bg: #0a0f0d (Black)", output: "Contrast Ratio: 13.8:1 [AAA PASS]" },
  },
  {
    id: "svg-optimizer",
    title: "SVG Optimizer & Cleaner",
    shortTitle: "SVG Clean",
    description: "Clean and minify SVG vector files by stripping editor metadata, comments, and unused attributes.",
    emoji: "📐",
    href: "/svg-optimizer",
    tech: "DOM Parser",
    steps: ["Paste SVG XML code or upload an .svg file", "Optimizer strips Illustrator/Inkscape bloat, unused namespaces, and comments", "Preview live vector output and download cleaned .svg"],
    tips: ["Vector editors add hundreds of bytes of useless metadata and editor tags", "Optimized SVGs load faster and can be inlined directly into React/Next.js components", "Lossless optimization preserves path coordinates and visual shapes exactly"],
    example: { input: "<svg ... inkscape:version=\"1.0\">...", output: "Clean SVG with 45% size reduction" },
  },
  {
    id: "screen-recorder",
    title: "Screen & Audio Recorder",
    shortTitle: "Screen Rec",
    description: "Record your screen, browser tab, or app window with microphone audio. 100% private, zero uploads.",
    emoji: "🎥",
    href: "/screen-recorder",
    tech: "MediaRecorder API",
    steps: ["Click Start Recording and select Screen, Window, or Chrome Tab", "Toggle Microphone option to record voice commentary", "Stop recording to preview video and download high-quality .webm"],
    tips: ["Runs entirely in your browser via HTML5 MediaStreams — no third-party recording software needed", "Choose 'Current Tab' with audio sharing to record web demos with system sound", "Recordings are saved directly to your local disk upon completion"],
    example: { input: "Screen + Mic stream", output: "screen-recording-2026.webm" },
  },
  {
    id: "audio-trimmer",
    title: "Audio Trimmer & Cutter",
    shortTitle: "Audio Cut",
    description: "Visual waveform audio cutter for MP3, WAV, and OGG files. Trim audio clips client-side.",
    emoji: "🎵",
    href: "/audio-trimmer",
    tech: "Web Audio API",
    steps: ["Drop or select an audio file (MP3, WAV, OGG, AAC)", "Inspect visual waveform and adjust Start and End time markers", "Preview trimmed segment and click Export to download clean .wav file"],
    tips: ["Decodes audio in-memory using Web Audio API — your music/recordings never leave your device", "Zoom into waveform to trim precise milliseconds", "Exported WAV files are uncompressed and universally compatible"],
    example: { input: "song.mp3 (3:45) -> Range 0:15 - 0:45", output: "trimmed-clip.wav (30s)" },
  },
  {
    id: "curl-converter",
    title: "cURL to Code Converter",
    shortTitle: "cURL",
    description: "Convert cURL commands into JavaScript fetch, Python requests, Axios, and Go code.",
    emoji: "🔄",
    href: "/curl-converter",
    tech: "Shell AST Parser",
    steps: ["Paste raw cURL command into editor", "Select target language tab (Fetch, Python, Axios, Go)", "Click Copy to grab ready-to-run API request code"],
    tips: ["Automatically parses headers, JSON bodies, basic auth, and query parameters", "Handles multi-line backslash continuations cleanly", "Outputs modern async/await syntax for JavaScript and TypeScript"],
    example: { input: "curl -X POST https://api.io -d '{\"a\":1}'", output: "fetch('https://api.io', { method: 'POST', body: ... })" },
  },
  {
    id: "cron-parser",
    title: "Cron Expression Generator & Parser",
    shortTitle: "Cron",
    description: "Parse and explain crontab schedules in plain English and calculate upcoming execution dates.",
    emoji: "⏰",
    href: "/cron-parser",
    tech: "Cron Engine",
    steps: ["Enter 5-field cron syntax or pick from quick presets", "Read human-friendly description breakdown", "Check next 5 scheduled execution timestamps"],
    tips: ["Supports step intervals (*/15), ranges (1-5), and aliases like @daily or @hourly", "Computes next executions relative to your local device timezone", "Standard crontab format: minute hour day-of-month month day-of-week"],
    example: { input: "0 9 * * 1-5", output: "At 09:00 on weekdays (Mon through Fri)" },
  },
  {
    id: "http-status",
    title: "HTTP Status Codes & Headers Explorer",
    shortTitle: "HTTP Status",
    description: "Instant searchable directory of HTTP status codes (1xx-5xx) and common request/response headers with RFC references.",
    emoji: "📡",
    href: "/http-status",
    tech: "RFC Directory",
    steps: ["Type any status code (e.g. 404, 502) or error name in search", "Filter by category tabs (1xx to 5xx or Common Headers)", "Click any code card to see RFC details, triggers, and common fixes"],
    tips: ["Covers all official IANA and RFC 9110 status codes", "Header tab includes Cache-Control, CSP, HSTS, and CORS explanations", "Copy status line format directly for mock server setups"],
    example: { input: "429", output: "429 Too Many Requests · RFC 6585" },
  },
  {
    id: "keycode-tester",
    title: "Keyboard Event & KeyCode Tester",
    shortTitle: "Keycode",
    description: "Interactive keyboard event inspector. Inspect event.key, code, legacy keyCode, and modifiers live.",
    emoji: "⌨️",
    href: "/keycode-tester",
    tech: "KeyboardEvent API",
    steps: ["Press any key or key combination on your physical keyboard", "Inspect large numeric keyCode, event.key, event.code, and modifier badges", "Copy the generated JavaScript event listener if-statement"],
    tips: ["Use 'Prevent default' checkbox to test Tab, Space, or function keys without scrolling", "Location indicator differentiates between Left and Right Shift/Ctrl/Alt or Numpad keys", "Keeps a history of your last 10 pressed keys"],
    example: { input: "Press Enter", output: "keyCode: 13 · event.key: 'Enter' · event.code: 'Enter'" },
  },
  {
    id: "json-to-ts",
    title: "JSON to TypeScript & Zod Schema",
    shortTitle: "JSON to TS",
    description: "Convert JSON objects into TypeScript interfaces, types, and Zod validation schemas instantly.",
    emoji: "📐",
    href: "/json-to-ts",
    tech: "AST Generator",
    steps: ["Paste valid JSON into input editor", "Choose output format (Interface, Type, or Zod)", "Copy generated type definitions or schema validation code"],
    tips: ["Automatically handles deeply nested objects and array element inference", "Zod mode includes z.infer<typeof Schema> type export", "Customizable root type name"],
    example: { input: "{\"id\": 1, \"name\": \"John\"}", output: "export interface Root {\n  id: number;\n  name: string;\n}" },
  },
  {
    id: "html-to-jsx",
    title: "HTML / SVG to JSX Converter",
    shortTitle: "HTML to JSX",
    description: "Convert raw HTML and SVG into React and Next.js compatible JSX with camelCase attributes and style objects.",
    emoji: "⚛️",
    href: "/html-to-jsx",
    tech: "Regex AST",
    steps: ["Paste raw HTML or SVG code", "Converter automatically updates class to className and style strings to objects", "Copy ready-to-use React JSX component markup"],
    tips: ["Automatically converts SVG attributes like stroke-width to strokeWidth", "Self-closes void tags like <input>, <img>, and <br>", "Transforms HTML comments into React JSX comment blocks"],
    example: { input: "<div class=\"box\" style=\"color: red;\"><img src=\"a.png\"></div>", output: "<div className=\"box\" style={{ color: \"red\" }}><img src=\"a.png\" /></div>" },
  },
  {
    id: "string-escape",
    title: "String & Regex Escaper / Unescaper",
    shortTitle: "Escape Text",
    description: "Escape and unescape strings for JSON, JavaScript, SQL, Regular Expressions, Shell, and HTML.",
    emoji: "🛡️",
    href: "/string-escape",
    tech: "String Encoding",
    steps: ["Enter text and select Escape or Unescape mode", "Choose syntax target (JSON, JS, SQL, RegEx, Shell, HTML)", "Copy escaped string for terminal or code"],
    tips: ["RegEx mode escapes all 14 special regex meta-characters", "SQL mode escapes single quotes (' -> '') and backslashes", "JSON mode properly escapes newlines, quotes, and control chars"],
    example: { input: "Hello \"World\"", output: "Hello \\\"World\\\"" },
  },
  {
    id: "css-generator",
    title: "CSS Glassmorphism & Shadow Generator",
    shortTitle: "CSS Generator",
    description: "Interactive visual generator for modern CSS Glassmorphism, Box Shadows / Glow, and Gradients.",
    emoji: "🎨",
    href: "/css-generator",
    tech: "CSS3 Engine",
    steps: ["Pick mode: Glassmorphism, Box Shadow, or Gradient", "Tweak sliders and color pickers with real-time visual canvas feedback", "Copy clean CSS snippet"],
    tips: ["Includes both standard backdrop-filter and -webkit-backdrop-filter vendor prefixes", "Shadow mode supports inset shadows and multi-axis spreads", "Gradient mode supports 3-color linear stops with custom angles"],
    example: { input: "Blur 16px, Opacity 15%", output: "backdrop-filter: blur(16px); background: #ffffff26;" },
  },
  {
    id: "hmac-generator",
    title: "HMAC Hash & Signature Generator",
    shortTitle: "HMAC",
    description: "Compute keyed-hash message authentication codes (HMAC) client-side for API auth & webhook verification.",
    emoji: "🔑",
    href: "/hmac-generator",
    tech: "Web Crypto API",
    steps: ["Enter secret key and message payload", "Choose algorithm (SHA-256, SHA-512, SHA-384, SHA-1)", "Copy Hex or Base64 digest, or paste signature to verify"],
    tips: ["Uses native Web Crypto API subtle.sign — your secret keys never touch any server", "Supports webhook signature matching for GitHub, Stripe, and Shopify webhooks", "Generate random 256-bit cryptographic keys with one click"],
    example: { input: "Secret: key, Msg: data", output: "Hex: 5031fe3d989c6d1537a013fa6e739ce23466faeccc73d4b3f165f37efbc93408" },
  },
  {
    id: "keypair-generator",
    title: "RSA & ECDSA Key Pair Generator",
    shortTitle: "Keypair",
    description: "Generate asymmetric encryption & signing key pairs in standard PEM format (PKCS#8 / SPKI).",
    emoji: "🗝️",
    href: "/keypair-generator",
    tech: "Web Crypto API",
    steps: ["Select key type (RSA 2048/4096-bit or ECDSA P-256/P-384)", "Keys generate in-memory instantly", "Download .pem files or copy public and private keys"],
    tips: ["Exported keys strictly follow SPKI (Public) and PKCS#8 (Private) PEM standards", "SHA-256 fingerprint displayed for easy public key verification", "Private keys are generated client-side and never leave your browser"],
    example: { input: "RSA-2048", output: "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8A..." },
  },
  {
    id: "password-analyzer",
    title: "Password Entropy & Strength Analyzer",
    shortTitle: "Password Audit",
    description: "Evaluate password complexity, Shannon entropy bits, and brute-force cracking resistance.",
    emoji: "🔍",
    href: "/password-analyzer",
    tech: "Shannon Entropy",
    steps: ["Type or paste password to evaluate", "Inspect entropy bits, strength rating, and character pool breakdown", "Review estimated GPU crack time and security recommendations"],
    tips: ["60+ bits of entropy is recommended for sensitive master passwords", "Calculates brute-force times against high-end 100B H/s GPU cracking clusters", "Checks for sequential patterns like qwerty or 12345"],
    example: { input: "Tr0ub4dor&3", output: "64 bits entropy · Strong · 35 years crack time" },
  },
  {
    id: "svg-converter",
    title: "SVG to PNG / JPG / WebP Converter",
    shortTitle: "SVG Raster",
    description: "Convert and upscale SVG vector files to PNG, JPG, and WebP at 1x, 2x, 4x resolutions.",
    emoji: "🖼️",
    href: "/svg-converter",
    tech: "Canvas Rasterizer",
    steps: ["Paste SVG markup or upload .svg file", "Select scaling factor (1x to 4x) and output format (PNG, JPEG, WebP)", "Download high-resolution raster image"],
    tips: ["Renders crystal-sharp retina images without raster blur", "PNG export preserves full alpha channel transparency", "JPEG export allows custom background fill color"],
    example: { input: "<svg ... width=\"400\" ...>", output: "rendered-vector-2x.png (800x800px)" },
  },
  {
    id: "color-extractor",
    title: "Image Color Palette Extractor",
    shortTitle: "Palette",
    description: "Extract dominant color palettes, HEX/RGB/HSL values, and CSS theme variables from any image.",
    emoji: "🎨",
    href: "/color-extractor",
    tech: "Color Quantization",
    steps: ["Upload or drop image file into workspace", "Algorithm extracts top dominant color swatches", "Copy HEX, RGB, HSL values or entire CSS variables block"],
    tips: ["Processes pixels client-side — your photos are never sent to a cloud server", "Generates ready-to-use :root CSS custom properties snippet", "Adjust palette swatch count between 4, 6, or 8 colors"],
    example: { input: "photo.jpg", output: "#4ade80, #06b6d4, #3b82f6, #101713" },
  },
  {
    id: "og-previewer",
    title: "OpenGraph & Social Meta Tag Previewer",
    shortTitle: "OG Preview",
    description: "Preview social share cards for Google, Twitter/X, Discord, Facebook, and generate HTML & Next.js metadata tags.",
    emoji: "🌐",
    href: "/og-previewer",
    tech: "OG Parser",
    steps: ["Fill in page title, description, canonical URL, and preview image URL", "Switch preview tabs (Twitter, Google, Discord, Facebook) to inspect appearance", "Copy generated HTML <meta> tags or Next.js App Router metadata object"],
    tips: ["Recommended OpenGraph image dimensions: 1200 x 630 pixels", "Title should stay under 60 characters and description under 160 characters for best SEO ranking", "Discord embed preview shows exact card formatting"],
    example: { input: "MegaTools - In-Browser Privacy Tools", output: "<meta property=\"og:title\" content=\"MegaTools ...\" />" },
  },
  {
    id: "ipv6-calculator",
    title: "IPv6 & Subnet Calculator",
    shortTitle: "IPv6",
    description: "Calculate IPv6 subnets, expand/compress addresses, compute reverse DNS ip6.arpa, and inspect address scopes.",
    emoji: "🧭",
    href: "/ipv6-calculator",
    tech: "Bitwise IPv6 Engine",
    steps: ["Enter IPv6 address in compressed or CIDR format (e.g. 2001:db8::1/64)", "View 32-digit expanded hex form and canonical RFC 5952 compression", "Inspect address scope (Global Unicast, Link-Local, Loopback) and reverse DNS zone"],
    tips: ["Standard RFC 5952 mandates lowercase hex and compressing the longest single run of zero groups", "/64 is the standard subnet size for IPv6 Stateless Address Autoconfiguration (SLAAC)", "Generates full PTR reverse DNS delegation records automatically"],
    example: { input: "2001:db8::1/64", output: "2001:0db8:0000:0000:0000:0000:0000:0001 · Scope: Global Unicast" },
  },
  {
    id: "docker-compose-converter",
    title: "Docker Run to Docker Compose Converter",
    shortTitle: "Docker to Compose",
    description: "Convert docker run CLI commands into clean, production-ready docker-compose.yml configuration files.",
    emoji: "🐳",
    href: "/docker-compose-converter",
    tech: "CLI Parser",
    steps: ["Paste single or multi-line docker run command", "Parser extracts ports, volumes, environment variables, networks, and resource limits", "Copy formatted docker-compose.yml spec"],
    tips: ["Supports multi-line commands with backslash (\\) continuations", "Automatically parses memory limits (-m) and CPU allocations (--cpus)", "Extracts restart policies, workdirs, and user overrides"],
    example: { input: "docker run -d -p 8080:80 nginx", output: "services:\n  app:\n    image: nginx\n    ports:\n      - \"8080:80\"" },
  },
  {
    id: "json-schema-generator",
    title: "JSON to JSON Schema Generator",
    shortTitle: "JSON Schema",
    description: "Instantly generate Draft-07 and 2020-12 JSON Schema validation schemas from JSON sample data.",
    emoji: "📜",
    href: "/json-schema-generator",
    tech: "AST Generator",
    steps: ["Paste valid JSON payload into the editor", "Select Draft-07 or 2020-12 schema standard and indentation", "Copy generated JSON Schema validation spec"],
    tips: ["Automatically detects date-time, email, and uri string formats", "Recursively traverses nested objects and array element types", "Toggle whether all object properties should be marked as required"],
    example: { input: "{\"id\": 1, \"email\": \"test@example.com\"}", output: "{\"$schema\": \"...\", \"type\": \"object\", ...}" },
  },
  {
    id: "markdown-table",
    title: "Markdown Table Generator & Editor",
    shortTitle: "MD Table",
    description: "Interactive visual matrix table editor for generating Markdown, HTML, and LaTeX tables in real-time.",
    emoji: "📊",
    href: "/markdown-table",
    tech: "Matrix Parser",
    steps: ["Add or remove rows and columns in the interactive matrix", "Click column alignment toggles (Left, Center, Right)", "Export to GitHub-Flavored Markdown, HTML <table>, LaTeX, or CSV"],
    tips: ["Click column headers to adjust text alignment (:---:, ---:, :---)", "Use row numbers to quickly remove unwanted rows", "Exports clean, copyable LaTeX tabular code for academic papers"],
    example: { input: "2x2 table", output: "| Feature | Status |\n|:---|:---:|\n| Speed | Fast |" },
  },
  {
    id: "bcrypt-generator",
    title: "Bcrypt Hash Generator & Verifier",
    shortTitle: "Bcrypt",
    description: "Generate secure Bcrypt password hashes ($2b$) and verify plaintext passwords against existing hashes.",
    emoji: "🔒",
    href: "/bcrypt-generator",
    tech: "EksBlowfish",
    steps: ["Enter plaintext password and select log2 cost factor (4-14 rounds)", "Click Generate to compute 60-character salted $2b$ hash", "Switch to Verifier tab to test candidate passwords against existing hashes"],
    tips: ["Cost factor 10 (1,024 rounds) is the industry standard for production web apps", "Everything runs locally in your browser — passwords are never sent to any server", "Supports verifying standard $2a$, $2b$, and $2y$ Bcrypt hashes"],
    example: { input: "mysecretpass", output: "$2b$10$N9qo8uLOickgx2ZMRZoMye..." },
  },
  {
    id: "device-inspector",
    title: "Browser & Device Inspector",
    shortTitle: "Device Specs",
    description: "Inspect browser hardware concurrency, GPU WebGL renderer, display DPI, network status, and battery level.",
    emoji: "🔍",
    href: "/device-inspector",
    tech: "Navigator & WebGL",
    steps: ["Open tool to automatically gather client device specifications", "Inspect CPU threads, RAM approximation, WebGL GPU unmasked renderer, and screen metrics", "Click Copy to export full structured JSON hardware report"],
    tips: ["Unmasks actual GPU graphics card vendor using WebGL debug extensions", "Detects exact Device Pixel Ratio (DPR) and monitor color depth", "Checks network connection latency and battery state where supported"],
    example: { input: "Client Browser", output: "CPU: 16 Cores · GPU: Apple M3 Max / RTX 4080 · DPR: 2x" },
  },
  {
    id: "email-dns-generator",
    title: "SPF, DKIM & DMARC DNS Record Generator",
    shortTitle: "Email DNS",
    description: "Generate compliant DNS TXT records for SPF, DKIM, and DMARC email authentication and anti-spoofing.",
    emoji: "✉️",
    href: "/email-dns-generator",
    tech: "DNS Builder",
    steps: ["Enter domain name and toggle authorized email providers (Google, Microsoft, SendGrid)", "Select SPF qualifier (~all / -all) and DMARC enforcement policy (none / quarantine / reject)", "Copy generated DNS TXT records directly into your domain registrar"],
    tips: ["DMARC requires valid SPF and DKIM alignment to pass delivery verification", "Use ~all (SoftFail) during initial setup, then transition to -all (HardFail)", "Include rua=mailto: to receive automated XML DMARC aggregate reports"],
    example: { input: "example.com (Google + SendGrid)", output: "v=spf1 mx a include:_spf.google.com include:sendgrid.net ~all" },
  },
  {
    id: "sri-hash-generator",
    title: "Subresource Integrity (SRI) Hash Generator",
    shortTitle: "SRI Hash",
    description: "Generate W3C Subresource Integrity (SRI) hashes (SHA-384, SHA-256, SHA-512) for CDN scripts and styles.",
    emoji: "🛡️",
    href: "/sri-hash-generator",
    tech: "Web Crypto API",
    steps: ["Paste JavaScript or CSS code, or upload a local file", "Generator calculates cryptographic SHA-256, SHA-384, and SHA-512 base64 digests", "Copy full <script> or <link> HTML tag with integrity and crossorigin attributes"],
    tips: ["W3C recommends SHA-384 for modern Subresource Integrity implementations", "Prevents XSS attacks if third-party CDNs are compromised", "Includes crossorigin=\"anonymous\" required for SRI script loading"],
    example: { input: "alert(1)", output: "sha384-H8BR2LUjQqWTuY0SDN39epLpmoYnBcUp0GLHehChwn68Z/6cDxPPOU9tMivIxyPenn" },
  },
  {
    id: "totp-generator",
    title: "TOTP 2FA Authenticator Simulator",
    shortTitle: "TOTP 2FA",
    description: "Generate standard 6-digit Time-Based One-Time Passwords (RFC 6238) from Base32 secret keys or otpauth:// URIs.",
    emoji: "🔑",
    href: "/totp-generator",
    tech: "HMAC-SHA1",
    steps: ["Paste Base32 2FA secret key or otpauth:// URI", "Live 6-digit token refreshes automatically every 30-second cycle", "Copy token or generate random 2FA keys for development testing"],
    tips: ["Compatible with Google Authenticator, 1Password, and Authy", "Paste full otpauth:// URIs to auto-populate issuer, account, and secret parameters", "Generates standard RFC 6238 HMAC-SHA1 tokens client-side"],
    example: { input: "JBSWY3DPEHPK3PXP", output: "852 914 (Refreshes every 30s)" },
  },
  {
    id: "ascii-banner",
    title: "ASCII Art & Terminal Banner Generator",
    shortTitle: "ASCII Art",
    description: "Convert text into stylish ASCII art FIGlet fonts and transform uploaded images into ASCII character art.",
    emoji: "🎨",
    href: "/ascii-banner",
    tech: "FIGlet & Pixel Luminance",
    steps: ["Type banner text and select ASCII font style (Standard, Slant, Blocks)", "Or switch to Image mode, upload a photo, and adjust character column width", "Copy formatted monospace ASCII output or download as text"],
    tips: ["Slant font works great for terminal CLI welcome messages and MOTD banners", "Image to ASCII converts pixel brightness into 70-character density ramps", "Invert mode switches between dark-on-light and light-on-dark backgrounds"],
    example: { input: "MEGATOOLS", output: " _ _  ___ ___   _ _____ ___  ___  _   ___\n| \\/ || __/ __| /_\\_   _/ _ \\/ _ \\| | / __|" },
  },
  {
    id: "clip-path-generator",
    title: "CSS Clip-Path & Polygon Shape Generator",
    shortTitle: "Clip-Path",
    description: "Interactive visual drag-and-drop CSS clip-path polygon generator with presets for hexagons, stars, and chevrons.",
    emoji: "📐",
    href: "/clip-path-generator",
    tech: "SVG Polygon Canvas",
    steps: ["Select a geometric shape preset or drag circular anchor points on the canvas", "Add or remove polygon vertices to create custom multi-point shapes", "Copy generated clip-path CSS declaration or Tailwind arbitrary class"],
    tips: ["Coordinates are calculated in responsive percentages (0-100%)", "Generates Tailwind CSS arbitrary property classes like [clip-path:polygon(...)]", "Preview with gradients, neon glows, or solid terminal styling"],
    example: { input: "Hexagon", output: "clip-path: polygon(50% 0%, 100% 25%, 100% 75%, 50% 100%, 0% 75%, 0% 25%);" },
  },
  {
    id: "aspect-ratio-calculator",
    title: "Aspect Ratio & Resolution Calculator",
    shortTitle: "Aspect Ratio",
    description: "Calculate aspect ratios (16:9, 4:3, 21:9), scale pixel dimensions proportionally, and find GCD reductions.",
    emoji: "📏",
    href: "/aspect-ratio-calculator",
    tech: "Euclidean GCD Engine",
    steps: ["Enter width and height in pixels or select standard 4K, 1080p, Ultrawide presets", "View simplified aspect ratio (16:9, 1:1, 9:16), decimal multiplier, and megapixel count", "Use the proportional resizing tool to calculate scaled dimensions"],
    tips: ["Uses Euclidean Greatest Common Divisor (GCD) for mathematically exact ratios", "Visual proportional frame renders exact shape preview in real-time", "Copies CSS aspect-ratio: 16 / 9 rule directly to clipboard"],
    example: { input: "1920 x 1080", output: "16:9 · 1.7778 · 2.07 MP" },
  },
  {
    id: "base58-converter",
    title: "Base58, Base32 & Base85 Multi-Converter",
    shortTitle: "Base58",
    description: "Encode and decode text and hex strings using Base58 (Bitcoin / IPFS), Base32 (RFC 4648), and Z85 algorithms.",
    emoji: "🔤",
    href: "/base58-converter",
    tech: "Radix Encoding Engine",
    steps: ["Choose encoding standard: Base58 (Bitcoin), Base32 (RFC 4648), or Z85 (Base85)", "Toggle between Encode and Decode modes", "Enter input string and instantly copy converted result"],
    tips: ["Base58 excludes visually ambiguous characters (0, O, I, l) and is used in Bitcoin and Solana", "Base32 is case-insensitive and used in TOTP 2FA secret keys", "Z85 encodes 4 binary bytes into 5 printable ASCII characters for ZeroMQ and network protocols"],
    example: { input: "Hello World", output: "JxF12TrwUP45BMd (Base58)" },
  },
  {
    id: "eth-unit-converter",
    title: "Ethereum Unit & Gas Fee Calculator",
    shortTitle: "ETH Units",
    description: "Convert high-precision values between Wei, Gwei, Finney, and Ether with EIP-1559 gas fee estimation.",
    emoji: "⟠",
    href: "/eth-unit-converter",
    tech: "BigInt Precision Math",
    steps: ["Select input unit (Wei, Gwei, Finney, or Ether)", "Enter amount to instantly calculate all equivalent denominations", "Adjust gas limit and gas price to compute estimated transaction fees in ETH and USD"],
    tips: ["Uses zero-loss integer math so 1 Wei precision is never rounded", "1 Gwei is 10^9 Wei and is the primary unit for Ethereum gas prices", "Includes presets for standard transfers, ERC-20 tokens, and Uniswap DEX swaps"],
    example: { input: "1.5 Ether", output: "1,500,000,000 Gwei · 1,500,000,000,000,000,000 Wei" },
  },
  {
    id: "eip55-checksum",
    title: "EIP-55 Ethereum Address Checksum & Validator",
    shortTitle: "EIP-55",
    description: "Verify EVM wallet addresses and encode lowercase strings to official EIP-55 mixed-case checksum format.",
    emoji: "🛡️",
    href: "/eip55-checksum",
    tech: "Keccak-256 Checksum",
    steps: ["Paste any 40-hex character Ethereum address", "Tool hashes address with Keccak-256 to calculate capitalization bits", "Copy official checksummed address safe for all EVM networks"],
    tips: ["EIP-55 prevents typographical transaction errors by encoding validation directly in letter casing", "Compatible with Ethereum, Arbitrum, Optimism, Polygon, and BSC", "Alerts you if an existing mixed-case address has a corrupted checksum"],
    example: { input: "0x5aaeb6053f3e94c9b9a09f33669435e7ef1beaed", output: "0x5aAeb6053F3E94C9b9A09f33669435E7Ef1BeAed" },
  },
  {
    id: "solana-converter",
    title: "Solana SOL / Lamports Converter & Inspector",
    shortTitle: "Solana Unit",
    description: "Convert between SOL and Lamports ($10^9$), calculate account rent fees, and decode Ed25519 public keys.",
    emoji: "🟣",
    href: "/solana-converter",
    tech: "Base58 & Ed25519",
    steps: ["Enter SOL or Lamports amount for instant two-way conversion", "Calculate minimum rent exemption balance based on account data size in bytes", "Paste Base58 address to inspect raw 32-byte public key and recognized program types"],
    tips: ["1 SOL equals exactly 1,000,000,000 (10^9) Lamports", "Token accounts require 165 bytes of data and ~0.002039 SOL rent exemption", "Identifies native System, SPL Token, Token-2022, and Metaplex programs"],
    example: { input: "1.25 SOL", output: "1,250,000,000 Lamports" },
  },
  {
    id: "keccak-calculator",
    title: "Keccak-256 & 4-Byte Selector Calculator",
    shortTitle: "Keccak-256",
    description: "Calculate Ethereum Keccak-256 hashes, Solidity 4-byte function selectors, and EVM event topics.",
    emoji: "⚡",
    href: "/keccak-calculator",
    tech: "Keccak-256 Engine",
    steps: ["Choose mode: Solidity function signature, UTF-8 text, or raw hex bytes", "Enter signature (e.g. transfer(address,uint256))", "Copy 4-byte method ID (0xa9059cbb) or full 32-byte hash"],
    tips: ["Ethereum uses original Keccak-256, which differs from NIST SHA-3 padding", "4-byte selectors represent the first 4 bytes of the Keccak hash of the canonical function signature", "Event topics use the full 32-byte Keccak-256 hash"],
    example: { input: "transfer(address,uint256)", output: "0xa9059cbb" },
  },
  {
    id: "merkle-tree-generator",
    title: "Merkle Tree Root & Proof Builder",
    shortTitle: "Merkle Tree",
    description: "Generate cryptographic Merkle roots and OpenZeppelin-compatible verification proofs for airdrops and whitelists.",
    emoji: "🌲",
    href: "/merkle-tree-generator",
    tech: "Sorted Pair Keccak",
    steps: ["Paste whitelist addresses into input (one address per line)", "Tool builds full binary hash tree and computes the 32-byte Merkle root", "Select any address to inspect its individual proof array or export full JSON"],
    tips: ["Follows OpenZeppelin's sorted-pair hashing standard (a < b ? a+b : b+a)", "Merkle proofs allow contracts to verify whitelist eligibility with minimal on-chain gas", "Exports full JSON claims manifest ready for web3 frontend integrations"],
    example: { input: "0x5B38... (4 addresses)", output: "Root: 0x999f... + 4 Proof Arrays" },
  },
  {
    id: "ai-model-comparator",
    title: "AI Model Pricing & Context Matrix",
    shortTitle: "AI Models",
    description: "Real-time cost calculator and specs matrix for 25+ LLM models with models.dev live sync support.",
    emoji: "🤖",
    href: "/ai-model-comparator",
    tech: "models.dev Open API",
    steps: ["Adjust input and output token sliders or pick a preset scenario", "Filter by provider (OpenAI, Anthropic, Google, DeepSeek, Meta, Qwen, Mistral)", "Click '$ sync models.dev' to pull live pricing data directly from models.dev into your browser"],
    tips: ["Estimates cost per prompt and cost per 1M tokens across all top frontier models", "Includes context window capacity badges (from 8k to 2M tokens)", "Highlights reasoning models (DeepSeek R1, o1, o3-mini) and vision capabilities"],
    example: { input: "10,000 in / 2,000 out", output: "DeepSeek V3: $0.0020 · Claude 3.5: $0.0600" },
  },
  {
    id: "ai-payload-converter",
    title: "Universal AI Payload & SDK Exporter",
    shortTitle: "AI Payload",
    description: "Convert system prompts and parameters into official JSON payloads for OpenAI, Claude, Gemini, and Ollama.",
    emoji: "📦",
    href: "/ai-payload-converter",
    tech: "Multi-Provider AST",
    steps: ["Enter system instructions, user prompt, model name, and temperature", "Toggle JSON mode if structured output is required", "Switch between OpenAI, Anthropic, Google Gemini, Ollama cURL, and Vercel AI SDK formats"],
    tips: ["Formats system prompts according to each provider's specific API requirements", "Generates ready-to-run Ollama CLI cURL commands for local model hosting", "Includes TypeScript Vercel AI SDK (streamText) export"],
    example: { input: "Audit Solidity code", output: "OpenAI JSON / Claude Messages / Gemini SDK" },
  },
  {
    id: "vector-similarity",
    title: "Vector Cosine Similarity & Distance Engine",
    shortTitle: "Vector Math",
    description: "Calculate Cosine Similarity, Dot Product, Euclidean (L2), and Manhattan (L1) metrics for AI embeddings.",
    emoji: "📐",
    href: "/vector-similarity",
    tech: "Vector Math Engine",
    steps: ["Enter Vector A and Vector B embedding float arrays", "Tool computes Cosine Similarity, Dot Product, Euclidean distance, and Manhattan distance", "Use presets to explore high similarity, orthogonal, or opposite vector angles"],
    tips: ["Cosine similarity measures the cosine of the angle between two embedding vectors in [-1.0, 1.0]", "Essential for building and debugging RAG (Retrieval-Augmented Generation) search indexes", "Supports arbitrary vector dimensionality (3D, 128D, 768D, 1536D, 3072D)"],
    example: { input: "[0.8, 0.4] vs [0.7, 0.5]", output: "Cosine Sim: 0.9938" },
  },
  {
    id: "secret-scanner",
    title: "Secret & API Key Leak Scanner",
    shortTitle: "Secret Scanner",
    description: "Detect leaked API keys, tokens, database credentials, and high-entropy secrets client-side with 1-click auto-masking.",
    emoji: "🛡️",
    href: "/secret-scanner",
    tech: "Shannon Entropy & Regex Heuristics",
    steps: [
      "Paste text, code snippet, .env file, or git diff into the editor",
      "Tool inspects lines for 14+ known key signatures and high-entropy strings client-side",
      "Review detected secrets with line numbers, severity, and entropy bits",
      "Click Auto-Mask to sanitize secrets before sharing or committing code"
    ],
    tips: [
      "100% client-side: no code or keys ever leave your browser or hit any server",
      "Shannon entropy identifies pseudo-random tokens even when vendor prefixes are missing",
      "Always revoke leaked API keys immediately even after masking or rewriting git history"
    ],
    example: {
      input: 'AWS_KEY="AKIAIOSFODNN7EXAMPLE"\nOPENAI_KEY="sk-proj-98af38bf8c..."',
      output: "Found 2 secrets: AWS Access Key ID, OpenAI API Key"
    },
  },
  {
    id: "pwned-checker",
    title: "Pwned Password & Data Breach Checker",
    shortTitle: "Pwned Checker",
    description: "Check if your password has been exposed in billions of leaked records using mathematical k-Anonymity privacy.",
    emoji: "🔓",
    href: "/pwned-checker",
    tech: "HIBP k-Anonymity & SHA-1",
    steps: [
      "Type or paste any password into the input field",
      "Web Crypto computes the 40-character SHA-1 hash locally on your machine",
      "Only the 5-character prefix is queried against HaveIBeenPwned's k-Anonymity API",
      "Inspect breach count, severity risk, and recommendations in real time"
    ],
    tips: [
      "k-Anonymity guarantees your password is never transmitted across the network",
      "HIBP only receives a 5-hex prefix shared by thousands of unrelated hashes",
      "If a password shows even 1 breach exposure, change it everywhere immediately"
    ],
    example: {
      input: "P@ssword1",
      output: "Breached 178,212 times in known data dumps"
    },
  },
  {
    id: "webrtc-leak",
    title: "WebRTC IP Leak & VPN Shield Tester",
    shortTitle: "WebRTC Leak Test",
    description: "Detect if your real public or local IP address leaks through WebRTC STUN requests even while using a VPN or proxy.",
    emoji: "🌐",
    href: "/webrtc-leak",
    tech: "WebRTC RTCPeerConnection & STUN",
    steps: [
      "Open the tool to automatically probe STUN ICE candidate generation",
      "Inspect discovered local (host) and public (srflx) IP candidates",
      "Compare WebRTC candidates against your primary HTTP public IP",
      "Follow step-by-step browser guides to disable WebRTC leaks if exposed"
    ],
    tips: [
      "WebRTC can bypass standard proxy and VPN tunnels at the browser engine level",
      "Modern privacy browsers like Brave and Tor randomize or block ICE host candidates",
      "Check both IPv4 and IPv6 WebRTC candidates for multi-homing leaks"
    ],
    example: {
      input: "WebRTC STUN Probe",
      output: "Public WebRTC IP: 203.0.113.42 · Host: 192.168.1.15 · Status: Shielded"
    },
  },
  {
    id: "dns-lookup",
    title: "DNS over HTTPS (DoH) Lookup & Records Inspector",
    shortTitle: "DNS Lookup",
    description: "Query A, AAAA, MX, TXT, CNAME, NS, and SOA records directly from Cloudflare and Google DoH resolvers.",
    emoji: "🔍",
    href: "/dns-lookup",
    tech: "Cloudflare & Google DoH JSON APIs",
    steps: [
      "Enter any domain name (e.g. google.com, github.com)",
      "Select specific record type (A, AAAA, MX, TXT, CNAME, NS, SOA) or 'ANY'",
      "Choose preferred DoH provider (Cloudflare 1.1.1.1 or Google 8.8.8.8)",
      "Inspect TTLs, record values, DNSSEC validation flags, and latency"
    ],
    tips: [
      "DoH encrypts DNS requests via HTTPS, protecting lookups from ISP snooping and spoofing",
      "TXT records are commonly used to verify domain ownership and configure SPF/DKIM/DMARC",
      "TTL indicates the remaining duration (in seconds) the record may be cached"
    ],
    example: {
      input: "google.com (Type A)",
      output: "142.251.12.101, 142.251.12.138 (TTL: 300s, Status: NOERROR)"
    },
  },
];

export const TOOLS_INFO: Record<string, ToolInfo> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t])
);

export function getToolInfo(toolId: string): ToolInfo | undefined {
  return TOOLS_INFO[toolId];
}

export interface ToolCategory {
  id: string;
  name: string;
  emoji: string;
  toolIds: string[];
}

export const TOOL_CATEGORIES: ToolCategory[] = [
  {
    id: "pdf-docs",
    name: "PDF & Documents",
    emoji: "📄",
    toolIds: ["pdf-merge", "pdf-split", "image-to-pdf"],
  },
  {
    id: "crypto-security",
    name: "Security & Crypto",
    emoji: "🔐",
    toolIds: [
      "password-generator",
      "uuid-generator",
      "hash-generator",
      "aes-crypto",
      "jwt-decoder",
      "file-checksum",
      "steganography",
      "security-headers",
      "cert-inspector",
      "binary-converter",
      "hmac-generator",
      "keypair-generator",
      "password-analyzer",
      "bcrypt-generator",
      "sri-hash-generator",
      "totp-generator",
      "base58-converter",
      "secret-scanner",
      "pwned-checker",
      "webrtc-leak",
    ],
  },
  {
    id: "media-qr",
    name: "Media & Audio/Video",
    emoji: "📱",
    toolIds: [
      "qrcode",
      "qr-scanner",
      "image-compressor",
      "image-converter",
      "exif-stripper",
      "favicon-generator",
      "screen-recorder",
      "audio-trimmer",
      "svg-converter",
      "color-extractor",
      "ascii-banner",
      "aspect-ratio-calculator",
    ],
  },
  {
    id: "format-text",
    name: "Format & Code",
    emoji: "📝",
    toolIds: [
      "json-formatter",
      "base64",
      "url-encoder",
      "text-diff",
      "text-transformer",
      "markdown-preview",
      "csv-json",
      "yaml-json",
      "sql-formatter",
      "code-minifier",
      "svg-optimizer",
      "curl-converter",
      "json-to-ts",
      "html-to-jsx",
      "string-escape",
      "css-generator",
      "og-previewer",
      "json-schema-generator",
      "markdown-table",
      "clip-path-generator",
    ],
  },
  {
    id: "dev-network",
    name: "Dev & Network",
    emoji: "⚙️",
    toolIds: [
      "timestamp-converter",
      "regex-tester",
      "chmod-calculator",
      "cidr-calculator",
      "port-lookup",
      "color-contrast",
      "cron-parser",
      "http-status",
      "keycode-tester",
      "ipv6-calculator",
      "docker-compose-converter",
      "device-inspector",
      "email-dns-generator",
      "dns-lookup",
    ],
  },
  {
    id: "blockchain-web3",
    name: "Blockchain & Web3",
    emoji: "⟠",
    toolIds: [
      "eth-unit-converter",
      "eip55-checksum",
      "solana-converter",
      "keccak-calculator",
      "merkle-tree-generator",
    ],
  },
  {
    id: "ai-llm",
    name: "AI & LLM Tools",
    emoji: "🤖",
    toolIds: [
      "ai-model-comparator",
      "ai-payload-converter",
      "vector-similarity",
    ],
  },
];
